apiVersion: v1
kind: Secret
metadata:
  name: garage-secrets
  namespace: garage
type: Opaque
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:siNWUVtIuNSF4fVFh68/HbxGicHyr8eBEaPoHK3Bzz/dFeqLzSxG4ES9oI4pjVSr5mu/soIqLgAeLdG3W8fnLQ==,iv:zwW5e3vWLiaoaBovaqR/hHdgUfu01a8AsvBYeYbY5cg=,tag:Mp8Ni1ZGwECtHYMcJBXpcg==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:FcZ/ObuOKsbzQteS+Pj9uwD40TsHbaP+I0iFnLQ1Y+pkyoSH5PeEdqO7Sn4=,iv:I1F00GzjJvScXVhUzn0jes+acryPLs5Fttmml6VU+z8=,tag:2ZrVz9mSeTNtY+rvLvU2kA==,type:str]
  GARAGE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:TyZHWGIVLh31lvfrtny6gbgP/YpCzywt+S4=,iv:o8xVVUeiThRTcjGFeErdH3wc2rfFn1XTHaaVq6qkp50=,tag:Aq4AVxF0sZ6QyAQ8bVWgbw==,type:str]
  GARAGE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c18+17W2wFEoaxp1OkhtY3W1lHomhJYy/2+Dr/RA4qGQSZ12e3QNImpUuTe6IDF4jroYnQ9Gy/YTuU4QO+uBZA==,iv:fQ5B1WucrzkpgX7cbxVqula6gAtLHCEPbor8ngxif6o=,tag:eC8ykka2phLQIzxwUtjLrA==,type:str]
  GARAGE_CI_CACHE_ACCESS_KEY_ID: ENC[AES256_GCM,data:qaBrRgNC8gcYiQ8f0RW5f2FTAD0=,iv:enwfN19dX7I0V6ktV05UDCYrzY9oSCtzTCIDnAp4lyo=,tag:ZqOhKKk8RoKacXYc6e4FBg==,type:str]
  GARAGE_CI_CACHE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TBQDUejVDLgUEeuXWZqAOdudeWtrpviPbxazMpce0ws7lyu3SAasTQ==,iv:LMvBRK5afZP27EEmXqMP3RncpqtuMNFi74nKKmP74pQ=,tag:oJ0mnJdq7/5VP0/uEK2W4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRHAvQUR0M1VvMkZMenpH
        eSsxbmU5N1IwNjBHWGhQYzUvZFNJY0dZRzIwCmhxQXNlQjg4UWcvUW9QNWV6anJE
        TjZWYWtUYkRpRWJiVkZSK0w5T1JoRDQKLS0tIHBWRFZyZ240SEVyUTh1elorWitz
        WVc0U0VvcnpxSmRkUkxMbDlhOG53TjQKl0nOm3CvI7xAIqN+ClRinO2I2Oa/R67t
        yEX3ht2HRKYNeGKeewCXeuGfD6joL9zjB7j06OxSNCtfpnD/76jZxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY2NPejBFQXNKQzR3a1dV
        a0srenJXYUxVQ3IzV1ZCbTNkY1pGQTV4a25NCmc4am01TkkvYlRyOFpaQ3A5OFdG
        d0ZrWnkzSXYrYXNKSzdGYTJQMVFuS2sKLS0tIE1aRFluZTNTVjg0VGRNbkRtckJM
        WG9vTlJ0Uno2eTZXa0lRTzc3WEROcW8KORXAd+JvHjwQjUcMQL53A51bUOZ6sJjz
        M3UBySLwrHRhlbL0XYgN61KUK5bUVMqNgLLXzBZpQFOB3zIRdkbFvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T02:25:02Z"
  mac: ENC[AES256_GCM,data:QEqgDnDo7VFTQh+agHtSMViUrLtjAOb5vmrECwOwNcWJ2QmsR7ZO5zTpssnt+5qvzbaXUQGFs8hu5q/ocsLUzjQZBVHe1J8UswIhr86hndFxF9nRZ6/cDWMExuaRXFBdAlzrcHAPu5hS6z/6VuGDFndQ2jUYbFZvoGuLrelIjGY=,iv:XAheAh1VGuir5F+LPVvjg79gDRDabwO1k6ok81+m+3w=,tag:r6SEjlS15E9cWcNPjnwzVQ==,type:str]
  version: 3.13.1
