apiVersion: v1
kind: Secret
metadata:
  name: garage-secrets
  namespace: garage
type: Opaque
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:siNWUVtIuNSF4fVFh68/HbxGicHyr8eBEaPoHK3Bzz/dFeqLzSxG4ES9oI4pjVSr5mu/soIqLgAeLdG3W8fnLQ==,iv:zwW5e3vWLiaoaBovaqR/hHdgUfu01a8AsvBYeYbY5cg=,tag:Mp8Ni1ZGwECtHYMcJBXpcg==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:FcZ/ObuOKsbzQteS+Pj9uwD40TsHbaP+I0iFnLQ1Y+pkyoSH5PeEdqO7Sn4=,iv:I1F00GzjJvScXVhUzn0jes+acryPLs5Fttmml6VU+z8=,tag:2ZrVz9mSeTNtY+rvLvU2kA==,type:str]
  GARAGE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:TyZHWGIVLh31lvfrtny6gbgP/YpCzywt+S4=,iv:o8xVVUeiThRTcjGFeErdH3wc2rfFn1XTHaaVq6qkp50=,tag:Aq4AVxF0sZ6QyAQ8bVWgbw==,type:str]
  GARAGE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c18+17W2wFEoaxp1OkhtY3W1lHomhJYy/2+Dr/RA4qGQSZ12e3QNImpUuTe6IDF4jroYnQ9Gy/YTuU4QO+uBZA==,iv:fQ5B1WucrzkpgX7cbxVqula6gAtLHCEPbor8ngxif6o=,tag:eC8ykka2phLQIzxwUtjLrA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVdiZGVEaG55cEV2TGEz
        SVZKZFV1L2N6T3cyb1lGZVpRRWtmSCtwV0hzClg5WTc3b1hoU1U5UFlJay8rb1k4
        bFFjS01ScVkxQXhsQW1QU3B2R0k1Y0kKLS0tIGIxemVPQW10QzQrRGNDZ05tTEJa
        elBJc1BUZ0V3ZEFjS1pYUUR2SHB1RkkKN27VP1NRiPi+rHY2vZ72guBFpQHHfb1H
        g/sktmZIytgxNQP87euQDRTCv71oyjfBfd8GnF6q4cUMBx/ymi0SWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQWd6Z2pHYVNrbjBQaTZK
        TzA2eDJkMGgyTkhVazcvZjdubnNzRWNLa0JVClp2dnRrTFFBMHAyL25lRWplenln
        T1hGQldLYS9sUmRUUS9LTEtwejUrM0EKLS0tIEliWk1vbFdWdkQxVWVoMlQ1UW5R
        dFpHNmNqL3lxSzR0NGZXb0tOMHowQ2sKfgm5RMQHiAMRQpcZhLEWUC9r0PhKSCrm
        kgnkzMjPpQ3WFabVHrnlhnIX8U5wWKSI4+Z/afT+pznB+tzvmxxVlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcTlNQWFpK09ucXNTN3Rt
        UFBUemNVeUZQeEFZZlV1SFJtUm8zWTI4Nng0CmErby9FdjJtRW9ZWDBNZzYvSmtq
        cUNLUUVidldFN0c2ek95NDMycC8xUlEKLS0tIHcvR1c3Q0paZWtyTnMzSS9tR0xh
        UXMwZ2FnWnZGa2tRN0hyK2RCK0FTRzAKREQAR6WdyBDFW7Xxa2hphE23tPyTqQYp
        3h7sHT2KVDCeLISmBWRAoMjOD9126CpHHmLs1W71kfJI0HatXha7mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-02T04:57:49Z"
  mac: ENC[AES256_GCM,data:JqyWGa442bhq6ueYF8RHSQegUmUT3wOcBUkYDD/a/41hMe06Nes1srg5VAr3/Sg94TnbCD2V+SBwu9T/6UIDpNxE11Crgv8ojfxKTGZCs0QHq8/dlZjCiHTYtgFFUnEYC4UA+CkpIjFG7Ff32csrCNH36vTNpV5SEc5iXMaVJno=,iv:SVFjLaiekLWhOVZfn1W6gj39mP4r5yMSsz/4ly4e89Q=,tag:LFbA1hMZYFVwa7a9jbmfFA==,type:str]
  version: 3.13.1
