apiVersion: v1
kind: Secret
metadata:
  name: zot-push-dockerconfig
  namespace: argo
type: Opaque
data:
  config.json: ENC[AES256_GCM,data:K7aRsDvHVUArTAv4iI4cbK95JO80lNO6PjdLNr1lz4ZToyk7EboRstFKZG70E9n3f8JqasiHvv9n9NZrBsVkDJpImxQnVhinwsD5VvvKAUeCFolCI667T61JbaS1CXeyN9YP/RF7/Q6D8cAdLwSD+oHj3i3P5UKwXxeR19TmWj/r8pcmwcTqqRC5yDDpBMNfB9XOm3RA+12sQk1bLe/wwQsBzZX3Z9IG,iv:UEylUmxBzs62MZD5gkdqueq+xMjPLWXXaJ7rwLaEy5M=,tag:nnLbAhSuEc55x02qcudwzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MlNKbkhrWHQ4RXFuQlJ2
        YkV0aGVCZjE2RXhoaFFHVFpJZmVBZ2E1VERzClJ3YzlSb2tFYWg0SkltaURQRmxt
        eWRVcWV3V0d1a3JXQW5GZTNGYU1KUjQKLS0tIHhQdHg5WEw5Zm5JT1NOQVNpeVIw
        OXNDdnUxd2ZlZkZrVXozSlIzcmdpNWcKGtLPOcIPGQX/heE9fSBaMpvmicYt3lfO
        i8fWwkI5Mg7UXL4UVe877Q6uCEjxNkpm2qEKoB/yNfb2n38677vG4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0K29UYVJzbjE5cmQxSGIr
        NmdCSEhuUEdSeW5WbWh1TEszTy81NDdaN0VVCnJXekVRQWhqV2FjSitBVEh0VXM3
        d0Yyb3Y4VVdpYzN6c2czRUcxWXIwMFkKLS0tIDJ6Y3pNVldObm9nK3QwQkZTYlJP
        S2F4cG1WTjFzQllORVdVTXI4SmIrWDQK0SNjSumkmxOY/eMFUUMpuDTC9bDq2XGR
        aryryWJ1Y6utSRIHveKHetUaLglmSobXa0hfsSvKwu19yHyB59czCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYWVuQXBob3JjbmRtZk5I
        WEdxcWJMbUQ5RU9GTXdNUHA4UjVVK3RaTVY4Ci9TZGZTcVIyaGxHSDV5SHRDa1l1
        WXBTdmtUa0ZjRk5HNmhzNUpvc3VwUVUKLS0tIEkySEsyNjNPZitoYk9HRDBUOHYr
        bEUydHBGRmtNNEJuL0txTVFPQjdOUGMKjQLlQ16phbIrAzXgX6oOFal5NoNt5+IS
        +3LWXlVAYcR5uojatu9TjKhEACCry8NSvWnw6NLD0hHtUMhGbUdnQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T01:40:31Z"
  mac: ENC[AES256_GCM,data:ntHbi2NXRn8r7pO3Myl3+cPH4+1JinlBtMYmvUQlUTUfeAgNGCd+ftl4qyO/TcMViDEVH/XGM/5TDYW4pSTo1CiLuBeiCKXNAKcU4Zfs9A4EbJox/gpeo8HKRUh2chM+p5q4o3wEJisuRIAbFk1olbGeYxppQ2D4s71sAQZ6cx0=,iv:bk0MmLWm73to5KFS6kCfxsFWPFSZsXVYuESYkFq0lVU=,tag:Fhbj88mGJROwm2hI9sQ0aQ==,type:str]
  version: 3.13.1
