apiVersion: v1
kind: Secret
metadata:
  name: zot-push-dockerconfig
  namespace: argo
type: Opaque
data:
  config.json: ENC[AES256_GCM,data:K7aRsDvHVUArTAv4iI4cbK95JO80lNO6PjdLNr1lz4ZToyk7EboRstFKZG70E9n3f8JqasiHvv9n9NZrBsVkDJpImxQnVhinwsD5VvvKAUeCFolCI667T61JbaS1CXeyN9YP/RF7/Q6D8cAdLwSD+oHj3i3P5UKwXxeR19TmWj/r8pcmwcTqqRC5yDDpBMNfB9XOm3RA+12sQk1bLe/wwQsBzZX3Z9IG,iv:UEylUmxBzs62MZD5gkdqueq+xMjPLWXXaJ7rwLaEy5M=,tag:nnLbAhSuEc55x02qcudwzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGtvNmtFQTByZ1B0ZXg2
        ckNONjc5ZUZKZE5YVjZmSlRpdlFNZFVOc21vCms3ZkNISCtLdFcwckNwa010SzNJ
        bmhpWnJKcm5DNTI4ZHlXeS93dzhxTjQKLS0tIDNCanhVQmRXQit4MkFFaHdSVlZM
        UHM0N0k5QXNocU9mNlVqUEczL0JSK1UKzA2XsF3l7Wgfsf3F6wDu6Dsm8fVZEwYH
        bvkb4HKHnRwMrv0n8qRkvVPKPyv0okmS34TyUHVDNgTZEkCg/tNstQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSzliWFZNRTdCR3gyWWNy
        bllqcGp1eUhqUDJKMi85NWI3NGpnVm82VEVBCkJJT3RFZjFTWEh3UHUxUGp5TThT
        Vm9NcDdQcjljcGNZZm9XOUZCTFNJS28KLS0tIE5Md0xWWVJJRVRWUk1rTU5RVWVR
        UFpxRGEwUHdJTzByeWp1TFJZSGlRWjAKfUXX7q4WNalusGXqKYEKU5GUvXhQYMsd
        I8CoMIsWBloxQXljXY3p++bTIpsEWBXTXmAnvr2bz7ZNqU0Bj6Ireg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T01:40:31Z"
  mac: ENC[AES256_GCM,data:ntHbi2NXRn8r7pO3Myl3+cPH4+1JinlBtMYmvUQlUTUfeAgNGCd+ftl4qyO/TcMViDEVH/XGM/5TDYW4pSTo1CiLuBeiCKXNAKcU4Zfs9A4EbJox/gpeo8HKRUh2chM+p5q4o3wEJisuRIAbFk1olbGeYxppQ2D4s71sAQZ6cx0=,iv:bk0MmLWm73to5KFS6kCfxsFWPFSZsXVYuESYkFq0lVU=,tag:Fhbj88mGJROwm2hI9sQ0aQ==,type:str]
  version: 3.13.1
