import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  ignorePatterns: [
    "apps/emdash",
    "packages/shadcn/src",
    "**/worker-configuration.d.ts",
    "packages/domain/src",
  ],
  jsPlugins: ["@roppoh/oxlint-plugins"],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  overrides: [
    {
      files: ["apps/roppoh/src/**", "apps/ura-roppoh/src/**", "apps/neo-fujimatsu/src/client/**"],
      rules: {
        "max-lines": ["error", { max: 150 }],
        "max-lines-per-function": ["error", { max: 100 }],
        "roppoh/file-structure": "error",
        "roppoh/no-cross-feature-import": "error",
        "roppoh/one-function-per-tsx": "error",
        "roppoh/prefer-alias-import": "error",
      },
    },
  ],
  rules: {
    "eslint/no-unused-vars": "error",
    "eslint/sort-imports": "off",
    "func-names": "off",
    "func-style": "off",
    "id-length": "off",
    "max-params": "off",
    "no-console": "off",
    "no-duplicate-imports": "off",
    "no-empty-function": "off",
    "no-magic-numbers": "off",
    "no-ternary": "off",
    "no-undefined": "off",
    "no-void": "off",
    "oxc/no-async-await": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/filename-case": ["error", { case: "kebabCase" }],
    "unicorn/no-anonymous-default-export": "off",
    "unicorn/no-null": "off",
    "sort-keys": "off",
    "new-cap": "off",
  },
});
