apiVersion: viaductoss/v1beta1
kind: ksops
metadata:
  name: ksops-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - monitoring/grafana-admin.sops.yaml
  - monitoring/grafana-object-storage.sops.yaml
  - monitoring/cf-workers-otlp-token.sops.yaml
  - argocd/argocd-notifications-secret.sops.yaml
  - cloudflared/cloudflared-tunnel-token.sops.yaml
  - discord-gateway-proxy/discord-gateway-proxy.sops.yaml
  - openclaw/openclaw.sops.yaml
  - hermes-agent/hermes-agent.sops.yaml
  - zot/zot-htpasswd.sops.yaml
  - zot/zot-object-storage.sops.yaml
  - garage/garage-secrets.sops.yaml
  - argo/zot-push-dockerconfig.sops.yaml
  - argo/build-github-app.sops.yaml
  - remote-dev/remote-dev.sops.yaml
