apiVersion: v1
kind: Secret
metadata:
  name: 9router
  namespace: 9router
type: Opaque
stringData:
  jwt-secret: ENC[AES256_GCM,data:6R3h3U2LLP/nIgEETOEaVt1hYLWpPS4mNHZScgJfmrkHir0radCHzrxBKfOeVT1t1pwLy48505QqcC7QVAzOIA==,iv:WcXIG55hW8/Ugli0Rcik4h/zeWRozyb+9LiMXGLSTPc=,tag:FNA3AZwANytl8Aam7qJEqA==,type:str]
  initial-password: ENC[AES256_GCM,data:1egwoyRa0uUpCegwDPOPQhACWt4=,iv:maLKmsF29HJ+VOIdMF9F4rr5XtTJxbNXkRHs7YRc09o=,tag:NrFo5gWaVMo/tHMjLZVZFA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4S1luY1g3eXJNYW5yeGpR
        eHhaMnNmSmxzR2V4TEwxTDdGckpBTk1qMndJClRuNU9CRjRCOHZCb0pLamZ3NFkx
        WUZnTmJnanhQMFNXS0krODF3WWZsaFUKLS0tIEJWamNvYllvZmxpVkdDbjdmdm45
        dG1DNW5oazAyUmtJanRKRjhSREw2QXMKfz3xUD+bVN6JxB3ODw7fTEUn+bSQWC9Z
        48kcNpbwi9cuQ+yY9viIYpH5cSm8pukhFro8cYXtPUFO82/PQ8Ueew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYWVRT3kyTTFJZlkyV0d6
        S0pWKzhzZ1dTUUhtVHIwZGRnTlFFcU1EOERjCnFSbldoUFdPM2hVUDBMSU5NZGFm
        SzAwc0ZYODBYNFRCNy93WUxBUVYwNGsKLS0tIG5QRGVCWjJhdmxPWkoxSUF4NUVW
        emtBb21OcUxoNzdrYk9hSXNGbmZ3L0EKk+o+8yOCVIBccz+Bc9ZU/KOJHVzZ+YBU
        l6ZRN8GlnEs1ac5NlKd3on2GOE/B2bzn22o1kXAVhDQM+qHboTaLig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTDVLb3BSTXIrdWJ5cUNR
        Vm05VHhoSWFNOXZEMFJoWGtvWlROSXZqS0dBClZtUy9sYUVjRjhueUc3RDlNWnFC
        d2I2dTYxWjdERVpCeEd2aC9NL1krWGcKLS0tIDU4ZHpjWkJ5MWpGYkJ4M0lIeWlv
        UW5vbXlOemxKd0JQM2JZRENnYWZWNmsK2ma67yUuiVmt1IiXkJOIM063l4fhmGtj
        E+evF3DNu7eSUKR/ZchXq0iGci+56d2qfq26AXFikq0nN3LxexOlEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-18T07:08:58Z"
  mac: ENC[AES256_GCM,data:V0jI4s47XLJZqjSZudccOJrDvPYbOP3MoWpMqHTOzR06yWenJmwebmPkF+irQJJ9EeDT82UF1ieTunvct0SSMfzXBA2d5lAojRV8H4OJKThr9KM4nUL3dsH0UP7nXyojGY0zZNPDDmdSZRCr5kqeIV3hEi7UMkLieLbWnhmg2+w=,iv:WA8ZtMSzvSzFqUvORpuIAiBqDNFCLiB2uW2VeFdeHgk=,tag:JgnyRnuvn6JzPIaN5ftUSw==,type:str]
  version: 3.13.2
