name: Setup Turbo Cache
description: Cache Turbo build artifacts

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v6
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: ${{ runner.os }}-turbo-
