apiVersion: v1
kind: Secret
metadata:
  name: zot-htpasswd
  namespace: zot
type: Opaque
data:
  htpasswd: ENC[AES256_GCM,data:8m3ERBIPSh2skQeJsE0EF3ercK+Yrz5/1ZUi7E04UjqgfIOwfPfTcBINh+r7AuqGkK3My36TzcNpR+s3IKyo43flxbu/91H1eD7lI6zRsa8anbc0,iv:J50C2zqtXAuHUaL8yQaAdtSW2qOmWjWbW8HUCw/OiR8=,tag:VUYLrAHOH/VnZvZ1XMqhcg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSTlyTEh1QjdwQ2NFQUhv
        UWNlcW5oWEdLUXlZc3hvdU5xRVpTVktzOEhzCkhXQms4dXNaQ0MzVHhTNGJneEF3
        MVp0UUpBajdQak10RVlxaGlYazdtYWcKLS0tIGpUN0ptUmI3QmtGMGw0ak9WaGJ5
        SUFkU1JXZWtSTFJoQVJBM3gvVHUzY1UKoSzoiMsDuBNSxaDho8j/CyG3a19tfApc
        xdYlcf33eu9rdRAIc3ppjSxwSfUThBRZJIzHwIQzgpitpQIMrfl9/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NDhGeGt6dGVPNFozVXBa
        REl0eGhLQm5jMkhlZk5GdUZOTzVkam5GdTBJCjBjMzZpWExiYmtBRXZQajZFdXpD
        Y2RpejN6MERNTnFBVW9VSDMzc0JmZUEKLS0tIDVJcnZHTnVVZlFxWXBXNkxjWktL
        amRKbzFUU1NhL2xLWTR5R01GNHhCVjQKvrgU6/3iB81a0e25eMnmnfNgD59ihHh0
        g5q+t9FJZxrQBoXaQLABntEz8ouVViCHJPOvbiJegX2IrFkTLv2yNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T01:40:31Z"
  mac: ENC[AES256_GCM,data:qo7y4vtb2lwOXeEJOhXiR3zBpYmpX61xPI2KoPq1LZGva+iRiQ5javNqFP5bnRYiTJuEB+3j1FLQE4LfXebtzR/jY7aQ+kTI0IEGpM1BtoyGmruh59cZamM+XL4Zxcq57UPdPtLR8C0o1dhZv0NY4J1c6DpO+jnvOABR8i7djZ0=,iv:g2aU8kP5cibDf9E4O7eHPVR10iorVGolngHb3TpxCgg=,tag:KuXeYdUqCb27qK0GsPrMkw==,type:str]
  version: 3.13.1
