apiVersion: v1
kind: Secret
metadata:
  name: zot-object-storage
  namespace: zot
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:F/kK7Jv+KTp0/EJehhKhwZOW4l0S7ebkMRtV5Nj9MTUPcH8I1qkA12GHDSY=,iv:UkchubkEDjrdOwQSi95oahI4DmaOVgzvCGcxqho23/Y=,tag:y+THcDJ0f3Z0LXALl/Go1g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kRMaAxCupBLg61ula4eO1bZrG2kvh6n/h14gLt665hW3aS9a22YP6ab5+I+pA7BSqoJ4y7mwtVAkA4ojZGaH3+wjWs0QLr2BVGUxgXQYaqkUWsJ69t1RKQ==,iv:lx1rMqShwGsbGIg9Ou0cw/8PcipE6lR1AFJZPRNjB5w=,tag:uRhgGSTcOjwtCHjZx/dTcw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cHVGQk9jNnhEYWJ2dzcy
        N2UraWE4MnF5MmloQWxsRmJuTVMxUzA1MUdzCjB0RUp3TGdHRmFNWUt4UUtSNTdE
        RnB1Tm82azFPMzZGSUFYTDcrM2ZFKzQKLS0tIFdwd1llb1A2a1M4cjRSU0lTR1Er
        OCtIb2IyaGRpNVU0R2lDTytUeS90ZjQKA0tPua1nQMTuntO2/dzN0sWN65XLvL1s
        VE6UvfhQvajcJfcf19Bm0Qekpex9WH5HFbbMW1+CFsapr7Do5J6gsg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQm4zS0IwaTAzQnhKR2oz
        UmFrUUlsem1oTnI2TjJRNVZxNWdOdmRyNFNJCjR5bXNrYkp1RXZrNE1CS1F5bzRH
        Y2ltdlp0RS9iQTFvay80U3hEK084SkkKLS0tICtPaWJObisxR2JpSnJEdE1ZV2dJ
        amJWTDdBZW1qeWZ6R0lLblgrbmh2SzAK2Dd5qy9jbB8Dc7Jsj9QGqfc2Gkqluxda
        a9w0Pjxuu6R0X7lwiHvrzZ5+hUx5BUlDOHOM4fR9KWmA9OKSw0Vbnw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T01:40:31Z"
  mac: ENC[AES256_GCM,data:hzU3nvT2hR8bUHRlp3XBy1ECRctuiNtICKreAfK0ML8e9h+3M3AnlUjpIHKMRf2HhBypPnabEisU53MaHNrcrRKgMb1tFTnk0ucKxoF3oBOj4plfn/4GFsn4NmxS4uayz66wyb7NZ5pf/nwkq4IRb1jJmFjtZc+8xfxlzqRsgVs=,iv:9tw4Yx24cuorZF/zC/FR05jFCfyG1rdpPUFudlZ0BiQ=,tag:PuX0WBU2eTAcMkVPGKcr7Q==,type:str]
  version: 3.13.1
