apiVersion: v1
kind: Secret
metadata:
  name: zot-htpasswd
  namespace: zot
type: Opaque
data:
  htpasswd: ENC[AES256_GCM,data:8m3ERBIPSh2skQeJsE0EF3ercK+Yrz5/1ZUi7E04UjqgfIOwfPfTcBINh+r7AuqGkK3My36TzcNpR+s3IKyo43flxbu/91H1eD7lI6zRsa8anbc0,iv:J50C2zqtXAuHUaL8yQaAdtSW2qOmWjWbW8HUCw/OiR8=,tag:VUYLrAHOH/VnZvZ1XMqhcg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSVc2VWhwdFJlKzJHNEx5
        N3hYMzh0MnV3VUlhSlNFMEZjQ2FIdFJpTkRBCnk1aDFiNG11dDlpdXMwbjI3M2ty
        V29nN2JQWGZIbUdvcDBwMW9lWUdoV1UKLS0tIFRQODhFRUJNN0s0SUJWaE9jSEln
        NUZUaDBTM1Biaks4dGVTWEJCODFJUjgKnLwvmx7rjdBrUR4+pkfRwFgQhjRim6bS
        Hd8N28tNHKbTpjAzpst8g/NWLQRuecdLjyvRWOUzmphYk93N4GLhaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cjhDWTlXRXRHQzFUOUQw
        QkZOV213U1c4ZlNZYTBMWFEzV3Jvc1NCZUZBClBmS05RY0dhOFV3YzZSVnUrNmx5
        aSswM0FJTm1xNjlhMTNTcjg3aFhud1UKLS0tIHJpNlZYSytRM2FaMWtTdGkyR1Vu
        QUx3UU95SzhSWS9hdVFrOWNNbWo1cDgKG04ZGgiqzbHg/OYFsAghUN93wfljTpGo
        jE9E11pPO+TYgQLRugU6RL+qrt9NnWE/1WbTR555l6BdLKQ1URj9ig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCS2FXa1REZVJuazRmV3ZS
        blhqMG5VekZFUmNISmo5SnZLcGM1RS9RQVF3CnZxbUQxRTI5QUVPbVFoaWhMc1BJ
        UW9WSXpEUkNWTmszemVUNTRPSEd5TEUKLS0tIDRNU01EanlubG80Z0M4VjZVR1JN
        K21wdUNtTzE0bGVTMDFFdnJiZ1JFYmcKOvAneD71B/f5viQgH92ZSNhGC9dA0zVP
        0hz0H/C+TRcjP+eMCDGjVbHsGVTrhNpKso7pWRv25eFFMHGYuNwYEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T01:40:31Z"
  mac: ENC[AES256_GCM,data:qo7y4vtb2lwOXeEJOhXiR3zBpYmpX61xPI2KoPq1LZGva+iRiQ5javNqFP5bnRYiTJuEB+3j1FLQE4LfXebtzR/jY7aQ+kTI0IEGpM1BtoyGmruh59cZamM+XL4Zxcq57UPdPtLR8C0o1dhZv0NY4J1c6DpO+jnvOABR8i7djZ0=,iv:g2aU8kP5cibDf9E4O7eHPVR10iorVGolngHb3TpxCgg=,tag:KuXeYdUqCb27qK0GsPrMkw==,type:str]
  version: 3.13.1
