apiVersion: v1
kind: Secret
metadata:
  name: zot-object-storage
  namespace: zot
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:e46P6Dz7UBxR16XRWO9I0SGQpMJR8bZovk4=,iv:vCE2/ysSoSZzUNferY1ZOcTk7of0uZEwx6GqDCVobbQ=,tag:w9syECdkDRAUvkVmEuLUBw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z7KcUzzBm6xuIHka8BHf0xAPZtIoPG5/IIlwZk2byYq/q35hgBeSexHfO9JJ41dE+TCrUFoerqC7FhKFy9eppg==,iv:SrYvhO0zeDJSCKUr0TKCApPElgkU4ZSk7r8RbWMskM4=,tag:nI7KQUVlT+uGcTxIbZBLbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWUJHRkN3TzFyQWJWY1h5
        aEhuRThtNUtDNXYzQ1I1Qml3TndFaS9NRXlnCnRaYlJ3U1VwRDFnUU83c0xFQUJt
        aDFHUzh1QTh6QzhYRTRtZlF6Z2RZYXMKLS0tIEx4R3pWdWwzZENScW1FRzNoZFlw
        Z2JVUXREenRtZmkrOGVVM2dneWJ2SjgKQrGgfUi76MFlOjjUfaT849Ziug1JFNej
        2qzraqExUtdVKQQEYJ1BUMc0ajfwXbfe9Hk8dTX0JJW5CzWlCpsg2g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMnpERDJLU25xdzZtWnJF
        bWk4TXYwczQ3OUw2aDdaeURSTEJaeVNCbVdJCmdMbTZhOXNvbEpYdkMvRXUzSEpU
        b2Q0RjAvakt3TG9JTnNyWGVSNDN2dUEKLS0tIHdCWjhwUU5oQ25ITytKQ3BrSzhz
        eDZSdkRNUzQ5dVgvK1RId3p6Q0hHRzAKMb/VaKMjalt+VcP5NARQVobHjDHQ7DbY
        KrGEpsH+xtJXiGWRtH89LVGiMQ14YUYlTX5EHSjJxtlYUgs+v25K/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ1RvcjQ1NEpCS2g4UVl4
        bjcxNnVXWjhRVGh0RndhVHBuR2dCYWRqY200Clp4elM1ZUdtMzhYQ0JHN1NLbjhR
        eklzR1Awbk9GZW5aVENvNFNwTk51ZEUKLS0tIHVLQmdVbnZVZFo3OVVRVTFhWnRR
        bStnd25MTWxLdFhLcjk4UmlKcmE2eW8K8Ii0rD2HKKn2aTjSOAu4jpAUv1+Nv1md
        XoE1eh1yqOpqQPUEG5c2O8LWLfg67veKFYHcqODW5S6vOFYKfU++ZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T15:44:46Z"
  mac: ENC[AES256_GCM,data:RppMF2lObrO5shvArMebY/YDz1V7D/uwBewVJ92SrCEoJTDt9LKvW9s5AHva0185d0BkLn4FfuClbTTbwyDDvzaP44aaht5nPbyEyHFYvH2H7jJ8nftuk2zWLGsR518dnqhy/07whAd41vBhVFuK78N9vDU2aFtmcmTD+J4h8RI=,iv:RsTfzM6AxpqMOLYqc2ijQAi9bD7ltf2wxeLvYvxTUfE=,tag:/89HV/Q9K9b4gkwsLDpgZg==,type:str]
  version: 3.13.1
