apiVersion: v1
kind: Secret
metadata:
  name: zot-object-storage
  namespace: zot
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:e46P6Dz7UBxR16XRWO9I0SGQpMJR8bZovk4=,iv:vCE2/ysSoSZzUNferY1ZOcTk7of0uZEwx6GqDCVobbQ=,tag:w9syECdkDRAUvkVmEuLUBw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z7KcUzzBm6xuIHka8BHf0xAPZtIoPG5/IIlwZk2byYq/q35hgBeSexHfO9JJ41dE+TCrUFoerqC7FhKFy9eppg==,iv:SrYvhO0zeDJSCKUr0TKCApPElgkU4ZSk7r8RbWMskM4=,tag:nI7KQUVlT+uGcTxIbZBLbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETDNUTHRkMTB2TnczeWR1
        b3hlMnFvQ25STkZYNWVNdDFvWGpUeE9naVJvCjhDdjlCRHdqUWRqZ3AyaFZPSXVU
        bWk0ZFowSzhPZldYa1FvdTBraVM0aHcKLS0tIEM1MXN0Q2V6VzEzRGVxV3NsZUhC
        OGM3ejU2bUY3MVNZNnI3VTJmS2J4SWsKIqqA2klBBWw7q8dlaQCuiEUkTw1jCDba
        UUCV9UV5oT9J8eURVGK2znblGZEXJEwmKVeZTOKMi443kAhHETfhKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVWxCejRYR2dkMmpkaUI2
        RngyZ3dkc2VHRzZXanUwbDQxeVdsbDhsMFVrCnJJbzFiNExwN1FBeGVIam94SGN0
        aDVUa2EzVHRkSjBuRkUzTGNmblgrR1EKLS0tIEM5aytmRGpXTXVQT1JRMGFJSGt5
        cjRoSDhrbWRSOFlHOFNxQ25mMHMvcEkKSyJV9YHV5nuqZBj+GcUNCqfiT/UUI2qH
        MD4zwaliUspxVf1MTguflvxIN+CmW/YkfxURwc3UyvLQtJfHkL/+uw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T15:44:46Z"
  mac: ENC[AES256_GCM,data:RppMF2lObrO5shvArMebY/YDz1V7D/uwBewVJ92SrCEoJTDt9LKvW9s5AHva0185d0BkLn4FfuClbTTbwyDDvzaP44aaht5nPbyEyHFYvH2H7jJ8nftuk2zWLGsR518dnqhy/07whAd41vBhVFuK78N9vDU2aFtmcmTD+J4h8RI=,iv:RsTfzM6AxpqMOLYqc2ijQAi9bD7ltf2wxeLvYvxTUfE=,tag:/89HV/Q9K9b4gkwsLDpgZg==,type:str]
  version: 3.13.1
