apiVersion: v1
kind: Secret
metadata:
  name: remote-dev
  namespace: remote-dev
type: Opaque
stringData:
  app-id: ENC[AES256_GCM,data:IC0Z82mtOdpJRZAU55WntUgb,iv:e76BBos5Jf7bgC16Mlbh/WDFJ23YezcSgqvXbdklS0k=,tag:ZCZuaGQnwIYWVyo6hL7pOQ==,type:str]
  installation-id-tsar-org: ENC[AES256_GCM,data:9l/m8zkx9H2MCopiTKnI4LG1m6SzVGtp0yAZaHE=,iv:UInlvXsXrD8mTa2Pkv99PtoOYVOClDCpUW/3/WwXqbk=,tag:xvQaDpMQLHN6x++RTrjiiw==,type:str]
  installation-id-taiki-kuraishi: ENC[AES256_GCM,data:dzauN/vg/UafHRuFsQBlEwAlAht1SV95/6VjgHL5N9VBTo0=,iv:+psNQ68GISyZ0TEoRfSkaMpbvBhM3agNYkb8HTaVb2E=,tag:Vucaszv/NEbdVMk8LD4P+g==,type:str]
  private-key.pem: ENC[AES256_GCM,data:aeek955baKj1V5TEP+olJI/Ylg4WbAp8VOxWhkS+1Q==,iv:GoglvJSbXC38dfQSdbVX1y/udSw3/p9G5jJDXv0OHh0=,tag:Qd78Qj5uIws11WYenImnIQ==,type:str]
  ssh_host_ed25519_key: ENC[AES256_GCM,data:ZUkSZlhRmUgSc55r+6bUzW8cVvfMNc/sZlvrkt8V7PaflXLUQ3ey8RSDWWIygWVZOAwaJcfAkkldJSvpvxXfI+2TO5lczhPSHbDGJQHxdnw/or2grYY5S/DPNUjXEUIryS5zOzEmXhTUIdjAuHmNhA0nCHbQAteSRjPypSU5KU5YNmK2QsmGCP4WJkZg96zHZv9ovNaPdIEmf1BaYq/I3rV9Hni5VwACKbyh/9iM3ZErxXXcefLwQbTyi9vcmkx9of6v+JM+e+utmggE+Ccg1dI8VRbocmO/eL5/zr4BYX1rC93nSNuWQ9t3eE8erfhEwYOfEZXGVFWuChKbvpfSitFN4rDFVINmZIZ99ngVLHG3W5+b6LTDaPu4ImNWr1jIjVHnxR0Rh19Sjni6xkeirlADenN/shYZ1yxxaEL6UdodzoTWdW+Xe7YiadECEZXDNNTYfkCZOLzfB439zfLMywszt21nyYWEaNlPC7W9fKzeqguQGX8K/gI9psfzGbWLcFKLcBaKMu7Om+tcb57O,iv:JllWzJDotE5i3Q2xbys60KP/PBfPStmjutQt/cTusJU=,tag:j/CwP+jixDbv1qywfg6nag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UE1WTTYvcVVINHNhemFq
        QjIzdjZVdGpKbEU5Mnc2OTAyRFZHV0Yya1ZFClN5TW1VeTJVVy83MEQ3NWlSeXJP
        TDBqNHdmNE8yLzF6NGpzNVYzREEvbE0KLS0tIEFqZW5rcytXME41ZnVYUG5kSTJM
        N0dvUm5RWGZLNHVIbDlsSXVxSG1MWVkKVyHZhkw413aSc1jsXW57PxsPk1Go3qQX
        qvcHm2+KaldcuPqSgTrBLtE5XKfXwwwGgxvTE0OakxwkloQWB4Sucg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNUhoY2Qxay9Hb3RwTkhW
        V0phbDZSS2Z2cC9IdTVtZTU4WFV5TDJmdjNNCkExT0lUaUQveVB1ZkdQOTRTdjRS
        czhBZDZXNXR5UDlYVERnU0dOeEFzWUUKLS0tIHpzemJMV3h5YVcvQmR4ejZiZjBm
        MmI0TC9Ga1c3SW9GakJQL2xHMFFqWGsKYj1qhanerJLfU32BPW+dxrlgTunvqMxk
        fAx3mDQzO2Xn3flM4aVXQwnuN4qCwKRdMTVJcKmoTt1LqEyfOkDiCQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T09:16:20Z"
  mac: ENC[AES256_GCM,data:4Zibp+MxbWyO3cq9k90aZ6SbgtYN+3YYtN/BoDVEn1366f4jJWJsFIinfbEEOUbsLm6srFKNbvKhXAw+Qg1muz/OM1mym8WVO17XuJaEAjX4aJhMSMk9f40VXWn8EvA5Q2jOJyjGm+3ub+caLMcwMn4f3ZFjXkKZiG/184Dl7w4=,iv:MhMKz7iRR5Baru8JMRJ+LcpfXosCVVcaqUu7I7fjkzQ=,tag:ex1V/SBNvl1iHPwD+ltPmg==,type:str]
  version: 3.13.1
