// Single codegen: reads the buf-built FileDescriptorSet and emits the three
// Downstream schema artifacts, controlling every byte so they bit-match the
// Current hand-written Terraform and Go producer.
//
// Run via `mise run proto:gen` (which runs `buf build` first). Do not edit the
// Generated files under src/roppoh/events/v1/ by hand.

import {
  createFileRegistry,
  type DescExtension,
  type DescField,
  type DescMessage,
  fromBinary,
  getOption,
  hasOption,
  ScalarType,
} from "@bufbuild/protobuf";
import { FeatureSet_FieldPresence, FileDescriptorSetSchema } from "@bufbuild/protobuf/wkt";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { type FieldModel, type Logical, type MessageModel, validateModel } from "./validate";

const PKG = "roppoh.events.v1";
const HERE = import.meta.dirname;
const OUT_DIR = path.join(HERE, "roppoh", "events", "v1");
const BINPB = path.join(HERE, "..", "descriptorset.binpb");

const GO_HEADER = "// Code generated by @roppoh/event-schemas (src/gen.ts); DO NOT EDIT.";

// Golint's initialism set, lower-cased. snake_case parts matching these are
// Upper-cased whole (guild_id -> GuildID) to match idiomatic Go / gofmt output.
const INITIALISMS = new Set([
  "acl",
  "api",
  "ascii",
  "cpu",
  "css",
  "dns",
  "eof",
  "guid",
  "html",
  "http",
  "https",
  "id",
  "ip",
  "json",
  "lhs",
  "qps",
  "ram",
  "rhs",
  "rpc",
  "sla",
  "smtp",
  "sql",
  "ssh",
  "tcp",
  "tls",
  "ttl",
  "udp",
  "ui",
  "uid",
  "uuid",
  "uri",
  "url",
  "utf8",
  "vm",
  "xml",
  "xmpp",
  "xsrf",
  "xss",
]);

function goName(snake: string): string {
  return snake
    .split("_")
    .map((p) => (INITIALISMS.has(p) ? p.toUpperCase() : p.charAt(0).toUpperCase() + p.slice(1)))
    .join("");
}

const PIPELINES_TYPE: Record<Logical, string> = {
  timestamp: "timestamp",
  string: "string",
  long: "int64",
  boolean: "bool",
};
const ICEBERG_TYPE: Record<Logical, string> = {
  timestamp: "timestamp",
  string: "string",
  long: "long",
  boolean: "boolean",
};
const GO_BASE_TYPE: Record<Logical, string> = {
  timestamp: "time.Time",
  string: "string",
  long: "int",
  boolean: "bool",
};

// Pipelines stream `required`: pointers/optionals are never required; otherwise
// An explicit override wins, defaulting to required.
function pipelinesRequired(f: FieldModel): boolean {
  if (f.optional) {
    return false;
  }
  return f.pipelinesRequiredOverride ?? true;
}

function goType(f: FieldModel): string {
  const base = GO_BASE_TYPE[f.logical];
  return f.optional ? `*${base}` : base;
}

// ---- read the descriptor set -------------------------------------------------

const registry = createFileRegistry(fromBinary(FileDescriptorSetSchema, readFileSync(BINPB)));

function reqExt(name: string): DescExtension {
  const e = registry.getExtension(name);
  if (!e) {
    throw new Error(`extension not found in descriptor set: ${name}`);
  }
  return e;
}

const tableExt = reqExt(`${PKG}.table`);
const namespaceExt = reqExt(`${PKG}.namespace`);
const logicalTypeExt = reqExt(`${PKG}.logical_type`);
const pipelinesRequiredExt = reqExt(`${PKG}.pipelines_required`);

// `getOption` returns a broad reflection type; the concrete shape is guaranteed
// By options.proto (+ validateModel). Isolate the necessary assertions here.
function optStrings(desc: DescMessage, ext: DescExtension): string[] {
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion
  return getOption(desc, ext) as string[];
}
function optString(desc: DescMessage, ext: DescExtension): string {
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion
  return getOption(desc, ext) as string;
}
function optBool(desc: DescField, ext: DescExtension): boolean {
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion
  return getOption(desc, ext) as boolean;
}

function deriveLogical(f: DescField): Logical {
  if (hasOption(f, logicalTypeExt)) {
    // oxlint-disable-next-line typescript/no-unsafe-type-assertion
    return getOption(f, logicalTypeExt) as Logical;
  }
  if (f.fieldKind === "scalar" && f.scalar === ScalarType.STRING) {
    return "string";
  }
  if (f.fieldKind === "scalar" && f.scalar === ScalarType.INT64) {
    return "long";
  }
  if (f.fieldKind === "scalar" && f.scalar === ScalarType.BOOL) {
    return "boolean";
  }
  throw new Error(`${f.name}: unsupported field kind/scalar (add a (logical_type))`);
}

function fieldModel(f: DescField): FieldModel {
  return {
    name: f.name,
    number: f.number,
    logical: deriveLogical(f),
    optional: f.presence === FeatureSet_FieldPresence.EXPLICIT,
    pipelinesRequiredOverride: hasOption(f, pipelinesRequiredExt)
      ? optBool(f, pipelinesRequiredExt)
      : undefined,
    scalarIsString: f.fieldKind === "scalar" && f.scalar === ScalarType.STRING,
  };
}

function messageModel(m: DescMessage): MessageModel {
  const tables = optStrings(m, tableExt).map((s) => {
    const [table, stream] = s.split(":");
    if (!table || !stream) {
      throw new Error(`${m.name}: bad (table) "${s}", want "<table>:<stream>"`);
    }
    return { table, stream };
  });
  return {
    goName: m.name,
    namespace: optString(m, namespaceExt),
    tables,
    // Field number = Iceberg field ID => canonical order, independent of source order.
    fields: m.fields.toSorted((a, b) => a.number - b.number).map(fieldModel),
  };
}

const collected: MessageModel[] = [];
for (const type of registry) {
  if (type.kind === "message" && hasOption(type, tableExt)) {
    collected.push(messageModel(type));
  }
}
// Stable output order: by first table name.
const messages = collected.toSorted((a, b) =>
  (a.tables[0]?.table ?? "").localeCompare(b.tables[0]?.table ?? ""),
);

validateModel(messages);

// ---- emit --------------------------------------------------------------------

// One entry per (message x table). Presence expands to two tables.
const pipelinesTf = messages.flatMap((m) =>
  m.tables.map((t) => ({
    stream: t.stream,
    table: t.table,
    namespace: m.namespace,
    fields: m.fields.map((f) => ({
      name: f.name,
      type: PIPELINES_TYPE[f.logical],
      required: pipelinesRequired(f),
    })),
  })),
);

const icebergSchema = messages.flatMap((m) =>
  m.tables.map((t) => ({
    table: t.table,
    namespace: m.namespace,
    fields: m.fields.map((f) => ({
      id: f.number, // = proto field number = immutable Iceberg field ID
      name: f.name,
      type: ICEBERG_TYPE[f.logical],
      required: pipelinesRequired(f),
    })),
  })),
);

function goStruct(m: MessageModel): string {
  const lines = m.fields.map((f) => `\t${goName(f.name)} ${goType(f)} \`json:"${f.name}"\``);
  return `type ${m.goName} struct {\n${lines.join("\n")}\n}`;
}

function recordsGo(): string {
  const usesTime = messages.some((m) => m.fields.some((f) => f.logical === "timestamp"));
  const parts = [GO_HEADER, "", "package pipeline"];
  if (usesTime) {
    parts.push("", 'import "time"');
  }
  for (const m of messages) {
    parts.push("", goStruct(m));
  }
  return `${parts.join("\n")}\n`;
}

mkdirSync(OUT_DIR, { recursive: true });

function writeJson(name: string, data: unknown): void {
  writeFileSync(path.join(OUT_DIR, name), `${JSON.stringify(data, null, 2)}\n`);
}

writeJson("pipelines.tf.gen.json", pipelinesTf);
writeJson("iceberg-schema.gen.json", icebergSchema);

const goPath = path.join(OUT_DIR, "records.gen.go");
writeFileSync(goPath, recordsGo());
execFileSync("gofmt", ["-w", goPath]); // Canonical alignment == records.go

console.log(
  `generated ${pipelinesTf.length} tables from ${messages.length} messages -> ${path.dirname(goPath)}`,
);
