apiVersion: v1
kind: Secret
metadata:
  name: openclaw
  namespace: openclaw
type: Opaque
stringData:
  gateway-token: ENC[AES256_GCM,data:EaCCXZCMmpdmcrTDODOJjCvrpiCprlQGSONT2zb8z5nEium7IzX67MIV59FSFPht4ohJ35QW2X8JpyOozw4fyQ==,iv:23tGRAeAmWgUTfemEkBJKGXCb/Y8UM2ggPp7/WNyiQ0=,tag:2LN961XXpSZ4oqwkazSy4Q==,type:str]
  discord-bot-token: ENC[AES256_GCM,data:lH3X36VjGCrunbg2WG1wPQ2UTOuDdoLRvC7ODMBAQdRYa6NBWe6N3q4SsnmK4Ry1I8ivnv+nO94f5i5sOjdhPfEYOKu+GaPs,iv:3vbu67RomG62RkfT2/p0aO9FkHMOl2U6BHFlxZVaeOw=,tag:YRWotMIFcjV2V7oxcAKnBQ==,type:str]
  github-app-private-key: ENC[AES256_GCM,data:hNNeBgajEgH9i/gRlcSy6lKq0kZPg9sogLco3riA8KHkAr16AJShuTdIFpLh/5yUqMLJVtv10lex5SnMHxJYVrX7o7HMS6N3h2qJdUAstJH3EZ3Y1NH9KmlzR3Mf3BcomNAH3QT+lsEpsotumbs+tVYXb8QydCm47Mxl4LY/ftMTK5MJxTxz3juilsr18wD2QyxbBXEZPh0FXb8nxh/0lpk1k23LccV678bmMH0JGcL+FYUrq4epCPRvZCtPn1gBE7/7Q4z2wv0aMCByIJol7NdooSiDW6a/U5ayB5Jxgn8EOEmXT8SY4fi8ACgn5HrudRnPYoqOLs1BtH7Elp29oSIwQuphC4Y+tajL6dI1W0KqX9kU+413GgMO0RO1oDCKxhvndZqUa0pzAXCJ07dFaCnyLX4gnDtaA25mI4ir5VoL74YzgA65DwDVM/0Y6d/5yRlns0BKo3mMafRhsr52xmSq1Ooz6yZITRqFr+DT0DVBKTlPbmviu13L400zBC2MdLiWIalILN8h1RgiMz1Vrt6HXmzf5ET5+P/aVszZxRJk8wIHC0bcPoJuS/9MXl5sSZNf9VRqAi/ziPBb6JKqdc6+4vs+jnHNA92l5JXww8IX0mkIGOKa6perds9io7bsAPHdzVa+ysLUj1fzYMO2VHL1ks5IA/dVqF+s/vCuNRz0aShAnEuvPwW7KuB1agWwDcIUtnAW6EvlWeN5zqQHgELnhAWHO5cQom8A0SL/ZHgURRTKkdmRhBeybPxP6/ElOXRf2D9w8GkYSNVJ4w9MfAlD3VRhHJFGDN6tSweQtbFDVDUAvpt296GHaVhJHkiiHWBGtXYVZv709lfe3JdalrFTxF1o7D5x3Xc9PviQQK6m+ZMNk8dujL2OHDFmzjGI5Atf8rUDkb/+zZXDwPBxrKz79uRWt95tAYZt1l/pHdpbuNRfYvDeUbbOd+Sr6LZ8GrnV8oK11fMhJ8CFcRbyp+7LDWteJ9UtPL6EsjNAxofTUIxWaNBc+DzyMk+y/kndl7+1aFI5kKSp01zE+LOp3FpGXDjLwhlVV0pGabKAH+W83vIaR/nFsyLP/cwYklLo6/FZ4Fu9uuyr8Tc5WHe9wwM7ifGozgzaMYTYlv3r9w9catsXZKdlbra4EpBb0XLYG6x1G4inSkZWwW2DlrKfU36VQYi4EdQOLk97ZR0dSB1JZL61rZiJmDFOLrjxIi6Ttk3KqqxdIdMdjrlz9W6P6FnBp98+lueK/2oqXzVmiD6AAjGhAyzGn2rgSmAzc3u6OtqUVFtu4Q5xOeYctvZDGV9CJlsAv5nSAn769tPk66TJ3cFaxLsYXu5Z416HCQ6/Qu1EyNmtN2NZKGH7tFi0KTAmZWMkgf6/ZAww08Odv7RQhLa1KbfP9Fmu1exlThealdClMGKtVJp0yb317/yX7f/sJvvZY92+u3Kdo9/MfgNqysF/GuwNOKAwbTEh5wV6OGI+hwVm1EDHORI8sqpZ53W7mu9E2/TQ4YFMuMU1VH1bubgio4VQKToGzPofi1AUIL83WGLI5f+us6teXGOnmcCVZM0DuSf0ErfzOghUOv03QBSInWcnaDSo98qV7cOcYdOBXdrmpm9FVzmyXn1QUOViPVkZYWPXEjOiid6r2oE4NXOxngJh8ato6sGppZG8XzfAtvkxRhKhbWQ4wGpylsJPxdFQ2gefx+mHPNL3uVDrlqW52zpRZc/zHITNMD7ijfZlpg5jrnTfSDsp8uU3JuTK5YR9LCwGJ6sCe/vfTOLk17BRLZtvR0DlRhyGqp2RfMINmsWy3KwvVLhIFa+6qAlcoOAjkXghQuVubHNL8CCQF+K3SmY5ByXKC23X/PuGKmgiF9hnnnzNvDhNYn3CmcqNT63XIjBW7OoWQWdlZuaaX+ZmTfhCvya86T7+2idSEJaJ0GjYNyL9xTIyudBFAMlofMqzaRmTJvVk43e5LeQB2CHmz46f6oCVev1QuzDpp7qjgz4Hzf/18M4m1B50HmXqkgHP4VuUa5G8kuhuu1TRAUUGGiz8cUa40idjre4oh/kyMWRklsGAVb7Kub9EDZ8f9hyTh2ZRr13QH4TPCeNjSMm0lmolyrnuveWUx9oXcwmiMJPEQ+KwHeiFiPzRWQIbR4FUB/jdrHJxKzuvsDQigl1zx8tCaWy/IftX8A5gOQKTT2uzAaiUl/ISA1wmqeIF3G2GR8yKlGIvUuSXFnn2LNmuIUaS2sk1HTfi7DY=,iv:MaqjF9SlrYMIh+0u0fC5z/OLas1XNyH8k9fnOop0PNE=,tag:iFnoAE5KuBX8zTf+9FE6LA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU1pvbkQwcHJTMjIxUDRp
        Rk1mQmdUd1lZd0pQMUpUYzBBamtTMkEyVEg4CmhBMlU4SVhEM2JNVG9HUmc2M042
        clNGOWNycytCWCttVzEyb3BXUjRWaE0KLS0tIDh5U2t3MVYxNXNpaXN2RWhmeUs4
        ZmFBYWhwVnF0Mnp5Y09XRzBKVHlSZ0kKrbNiAJs71LzUzRQZjKU7vQE0IIB6J1C0
        2yKZMA1udmEYE8YzqP9JUDqxrTDQ81f9aBniLbJJcNAndVe9dXPqLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dWQ2WFdlbXltQVVMSTcv
        YnlwU1dxaEhJQzl6UEtmZ0J6QTJjaDJHWUNBClFvWkcxYmIzMWVtRkY4NUhlUWMy
        Q1VQTUt3UE1qMDVwSHVvSWc4eDd2Q1UKLS0tIGwzVkZoMmswNFlRZFdWMUJnSlJL
        Tk9NZE0xN2sxb3d6NWx6TlJlc1FTQkUKkfRk6RyrjAx5T6SqcSfBFPUeOukRjlce
        rvVWBWOElQfvNcPI2N6PFXzHC+sRt7UxmWDFARpabFbK17yjxoUeLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByODE0ZksxQnRhYWNUb2tz
        OUhWQ1lYaUh2aXg3YUpVd1Q1cURXbUNrdUJZCkRJVFNvS1BCTFo4cXBWalZQSnZl
        c0NWNGpud1JhdTZhUUkybStlUkVDL0kKLS0tIG9XTzByZy92bzhZb0tsYlBpVEpL
        akhUVDVvN2plMTkrcnFvUE1LL00zYU0K6b1xb4s/iY3iJVpLHLNHIircNCTuaBzR
        GOVfRQLGky8VRcdRYjErYC/2eLli68cl3yu4UTGCrZS/2IjImjGH3w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T12:38:16Z"
  mac: ENC[AES256_GCM,data:crSMGZuXQ0Y9MruON2xegVZ+OqhilOLNXCXGPgTrqQk95EzEjPHJb+Rf7YxvLWgslybiq0Jfp64Yc5NBp89W220LcQ4xkrs02+3vukk40wCKzjiLaMGCgXP8XAuYPdspBKyubYmct7fQOyAf8mDng0Mi+d+seMLV+3Er69jxxeY=,iv:pNTr0paGO1UhtvbOVfrq78vJZ8kzyvhzYOpRI4qxGZY=,tag:gu8LXnBWNx0sajM9olasJg==,type:str]
  version: 3.13.1
