apiVersion: v1
kind: Secret
metadata:
  name: openclaw
  namespace: openclaw
type: Opaque
stringData:
  gateway-token: ENC[AES256_GCM,data:EaCCXZCMmpdmcrTDODOJjCvrpiCprlQGSONT2zb8z5nEium7IzX67MIV59FSFPht4ohJ35QW2X8JpyOozw4fyQ==,iv:23tGRAeAmWgUTfemEkBJKGXCb/Y8UM2ggPp7/WNyiQ0=,tag:2LN961XXpSZ4oqwkazSy4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMWNvREpGREZGTmxkZWp5
        b09FT1h2dzhJVHZSV3ZoeHlJWTdIOWYwaXpzCldDS1kxdmVsRmZhTTk1bHZYNFNO
        dGp6enpac1p1alByY2Q3YmlNUk00eHMKLS0tIGU5S1R3ckNnNWt1bk9mSTZETjNP
        MHppVFJOek5Ycnc4OTJwZFd1aTFOSkUKeqxBqI/dXPckFCDG2aPE65Sh8cGmGaVJ
        S9ES/LAwTi1lyUDWDbyH/zaRSSMJBgZwQbnExI9ylfZfe3adorwdIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWVAwaC9HMUowU2xTMHV5
        K0ZlWm52S0dRRFNkVlhieXdCT01OQUo5ZUR3CjRZV3E4VVRyY0JFeHo1ODI2OTJE
        QlQ0L1h2T3BIY2JIUGRvaGhwQjJxbVUKLS0tIGw2QWVPM21BMFBUK1IwcjIvWFRR
        dmdURWh3WENPY1hkcnVEaXZKMkFqVlkKsSwVk2qidgAIyDkW4nf2Be/rMuGZKU/V
        JZLlhwojzDgb4xeiZBOle5QFg9lIYxi0rHcgl+KPX0aEkODpCQioRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T06:41:02Z"
  mac: ENC[AES256_GCM,data:qjTuhNO1eNWh49DyYce7dpC2+dsYD8PKOesmSNZ8CjKgYllt7MTlKwmI5NEesDRbWoeN46orjj03YImHha4qikXB8pG7adqoSQkNVdz+1Io7GUMg1I3su61fKptACNbMEiyNJRydS+je+1sZU2yVFw0j7w1+qHi0o3UOicwxXyc=,iv:+hHg2bDYv/+FvYb/UkcC2gjvUIEutSMgPH2+8aZU5Ls=,tag:dvpoesW7Z4Ub2NKnEy6YtQ==,type:str]
  version: 3.13.1
