apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:1krY0GXlqkUSSjNja3sHg36UZJdHWgutv0BS+nonnt9JHtkdGZa3OKf2ZyMxP16UhM8Xl5dtUwzY12LgJZFESnLmjlGBwU8rutfAO1apCr2hMWoFnVq3+s29vF6bNn/UtRmEmW+6WryOipMn8g4rMEMQLHzYuspw5GzihsjCAJoeemBGntEMtLVflTeui4POQxTCslhVqN0nIRivP6fmIRtK9POvnbkEjj7729YhGoABZv71yby0oA==,iv:lYXe4T17l85tmv8tmT+U/5XfMIGjOpthHxVNKCgcUo4=,tag:+IInpWh+BKTL/5HYfp6BjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUGNEazYrNkdJdmN4bGJJ
        WVczZWY1bDAvQnV0M0dIeXJyR3U1em1sTHhJCjdjQ0YrQTNvTEJkT2VldHJkanVs
        SVpIblJzakY1QjVGVFVPZmNlSUJCNzgKLS0tIHhjcWMyZlVweEVuQUpHY1NBQk1V
        WkFxV0pwN0NsVlBkbUVzeVdYWm01NW8KSlEP2MMhC7xSvBwWdgATVhuG3AqhS6C8
        lPFTFSpjST2qDdvZzf/ad7TssUfcZvqbMgB3NLdfClGAMjGCQADOyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUEJJK0dXcS9UVDVyQ1dI
        WEFZQ2FuU2t6V0F3NERFeEJ0RS9qVkdFWlhrClJyUU9RRjBLclBpUER4Z29PUGM1
        VDgyN2JFVDQvbWlvM3ZzZHA0N3dpWHMKLS0tIHFjOU5tTTFvM0gvbzNGVUorVlVZ
        VTc1Nmo2NUtlR01rRWNiS3M3eUNUNVUKIEq+tq97Ded7nWeXKxZret4d4zStRQr3
        +Wrpl6rmlaYcORbPl/Q5+zXm2aMPZKnxcQNRFa413t9M4W8gx5oW4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMlAzZGpjM2ZEZ0pQcW1D
        QmFualJnRTV1WEdGdi9NOVp6WGRZbDlkV1VvCkR5WUY3NGM4WXd3M3g2WjNvbkFW
        T0ZtZ1lVS3IvUUxHRWdXZFpXbEp2RWsKLS0tIEIzWjNmb1RFN3ZWWEMwTjExL0p4
        MVlYa2xTMWIxMkE1Vm83YVRzV3QxTGMKMlaNxNym5jmDQl5edoj8kjqUekB+hF32
        xCfTjQ+O8HAhvFBZJV93kTrqRW/W3KUI9Bf8po4VdzIicO1+rZfsrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T11:31:36Z"
  mac: ENC[AES256_GCM,data:4SRuqsU5WhtLrZW+5z+CSmol+vbCiMwu4b8De1iRSztsavVEZFA3YusHJxoHeCBLm7ezbPTNkW+JYov2oBuBW6JpGT8oVcdgjSwel9sKCRWS8Z/TeF5/xrlLpyAt9fNPBrTpOxOIWTbQz2310UcV6VKaEGF1fxVGHMc7a7BMu3w=,iv:Vw/tLRpuUkBn8OMyDravKQFHxLK1Or8v/NLOsBJPkCA=,tag:QY+ok5lF7PJRoYzckZBACA==,type:str]
  version: 3.13.1
