apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:1krY0GXlqkUSSjNja3sHg36UZJdHWgutv0BS+nonnt9JHtkdGZa3OKf2ZyMxP16UhM8Xl5dtUwzY12LgJZFESnLmjlGBwU8rutfAO1apCr2hMWoFnVq3+s29vF6bNn/UtRmEmW+6WryOipMn8g4rMEMQLHzYuspw5GzihsjCAJoeemBGntEMtLVflTeui4POQxTCslhVqN0nIRivP6fmIRtK9POvnbkEjj7729YhGoABZv71yby0oA==,iv:lYXe4T17l85tmv8tmT+U/5XfMIGjOpthHxVNKCgcUo4=,tag:+IInpWh+BKTL/5HYfp6BjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRmRSR0Yyb1BYYW1UbUsy
        OGEzMVRseWhCM1c3R0Fwa0ljR3QwSW9rOGtVCktUajdVVlhoOHY4SlR5V2J2UE9G
        d2lpbk1GV0krVnZJU1g3SmpQZUErb1kKLS0tIEp5a1YvblI5ekZOYXlRSDlVV01W
        L1R0MXk5NTlEK0N3YlN0dVFwa1c4QUUKZKVw89gRDjyzx7FAraC2h0mtXpJa4AYC
        rW5cjArptaiFR5amGYiM5O1BKs9+vhnyngKTeIWz3X+62qppRGiJXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ2hpeG9uaklWT1hBOUFt
        cy9OQ2JDWkpkOVZFR1Y2MXVvS2dLTzVwM21FCjB5MzBvZTVNaXVac29MQThpQ3Bx
        Z1lnUXIya29NWVpWSmVlQk92QWt3VHMKLS0tICs4ZTRmZWVjSEw4M3RmWmplbUxN
        enhaeHArQ2k2T3lLcXRGYWZTWTZTOEEKN7OjupdRI5vygVnl5V5z3Wmy++c+Uwiw
        GmJxQjgfY5CvB2AMhyX5IgDOsUkcLCZ91C5wxh5ipZ6vvyXv+iDt7w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T11:31:36Z"
  mac: ENC[AES256_GCM,data:4SRuqsU5WhtLrZW+5z+CSmol+vbCiMwu4b8De1iRSztsavVEZFA3YusHJxoHeCBLm7ezbPTNkW+JYov2oBuBW6JpGT8oVcdgjSwel9sKCRWS8Z/TeF5/xrlLpyAt9fNPBrTpOxOIWTbQz2310UcV6VKaEGF1fxVGHMc7a7BMu3w=,iv:Vw/tLRpuUkBn8OMyDravKQFHxLK1Or8v/NLOsBJPkCA=,tag:QY+ok5lF7PJRoYzckZBACA==,type:str]
  version: 3.13.1
