apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:1krY0GXlqkUSSjNja3sHg36UZJdHWgutv0BS+nonnt9JHtkdGZa3OKf2ZyMxP16UhM8Xl5dtUwzY12LgJZFESnLmjlGBwU8rutfAO1apCr2hMWoFnVq3+s29vF6bNn/UtRmEmW+6WryOipMn8g4rMEMQLHzYuspw5GzihsjCAJoeemBGntEMtLVflTeui4POQxTCslhVqN0nIRivP6fmIRtK9POvnbkEjj7729YhGoABZv71yby0oA==,iv:lYXe4T17l85tmv8tmT+U/5XfMIGjOpthHxVNKCgcUo4=,tag:+IInpWh+BKTL/5HYfp6BjQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQTFIbUttd1VPOTFxLzRP
        MGdpTjcxQzE0ekd4RXpsbkR3dFh4ZjNzUVM4CjdGbHQ1VjVNWWxlM01GNVlSMTlK
        NXNIZWIxajB5bmIxcVJaQ1dYdzg3MXcKLS0tIEV0RG5BQXkwV1ZKQytCYkwveDNV
        L0JLR3dvb2hIRG9wZ3RrdDNtb3k4Um8KNtIboYMzEWUCyH9Zsaq+HJduwgqhWH2h
        2WgCxSzLSI+PcOeoz+q+9tbRVHQB7gPZVoOQSmDKmdzxike9UOA/6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T11:31:36Z"
  mac: ENC[AES256_GCM,data:4SRuqsU5WhtLrZW+5z+CSmol+vbCiMwu4b8De1iRSztsavVEZFA3YusHJxoHeCBLm7ezbPTNkW+JYov2oBuBW6JpGT8oVcdgjSwel9sKCRWS8Z/TeF5/xrlLpyAt9fNPBrTpOxOIWTbQz2310UcV6VKaEGF1fxVGHMc7a7BMu3w=,iv:Vw/tLRpuUkBn8OMyDravKQFHxLK1Or8v/NLOsBJPkCA=,tag:QY+ok5lF7PJRoYzckZBACA==,type:str]
  version: 3.13.1
