apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-app-deployed.github: ""
spec:
  project: default
  source:
    repoURL: https://github.com/taiki-kuraishi/roppoh
    targetRevision: main
    path: k8s/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
