apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - cloudflared.yaml
  - ollama.yaml
  - nvidia-device-plugin.yaml
  - grafana-loki.yaml
  - grafana-mimir.yaml
  - grafana-tempo.yaml
  - grafana.yaml
  - grafana-alloy.yaml
  - kube-state-metrics.yaml
  - dcgm-exporter.yaml
  - argo-workflows.yaml
  - zot.yaml
  - garage.yaml
  - discord-gateway-proxy.yaml
  - discord-gateway-proxy-build.yaml
  - openclaw.yaml
  - hermes-agent.yaml
  - grafana-dashboards.yaml
  - secrets.yaml
  - traefik.yaml
