apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-app-deployed.github: ""
    notifications.argoproj.io/subscribe.on-app-degraded.discord: ""
spec:
  project: default
  source:
    repoURL: https://github.com/taiki-kuraishi/roppoh
    targetRevision: main
    path: k8s/minecraft
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
