apiVersion: v1
kind: ServiceAccount
metadata:
  name: renovate
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
