name: Setup Go
description: Setup Go toolchain with module cache

runs:
  using: "composite"
  steps:
    # Keep this version in sync with the go version specified in mise.toml
    - uses: actions/setup-go@v5
      with:
        go-version: "1.26.4"
        cache-dependency-path: go.sum
