apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: remote-dev

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: remote-dev-authorized-keys
    files:
      - files/authorized_keys
