// Code generated by @roppoh/discord-events-schemas (src/gen.ts); DO NOT EDIT.

package pipeline

import "time"

type PresenceRecord struct {
	ReceivedAt      time.Time `json:"received_at"`
	GuildID         string    `json:"guild_id"`
	UserID          string    `json:"user_id"`
	Status          string    `json:"status"`
	ClientDesktop   string    `json:"client_desktop"`
	ClientMobile    string    `json:"client_mobile"`
	ClientWeb       string    `json:"client_web"`
	ActivityName    *string   `json:"activity_name"`
	ActivityType    *int      `json:"activity_type"`
	ActivityState   *string   `json:"activity_state"`
	ActivityDetails *string   `json:"activity_details"`
}

type VoiceRecord struct {
	ReceivedAt time.Time `json:"received_at"`
	GuildID    string    `json:"guild_id"`
	UserID     string    `json:"user_id"`
	ChannelID  string    `json:"channel_id"`
	SessionID  string    `json:"session_id"`
	SelfMute   bool      `json:"self_mute"`
	SelfDeaf   bool      `json:"self_deaf"`
	Mute       bool      `json:"mute"`
	Deaf       bool      `json:"deaf"`
}
