apiVersion: v1
kind: Secret
metadata:
  name: discord-gateway-proxy
  namespace: discord-gateway-proxy
type: Opaque
data:
  bot-token: ENC[AES256_GCM,data:UtEtivp2IDpk4XvC85ICyJMYqsfXlyWaS0/pjLUQWPsI5BzNWSB5/7NdsGM2GkJsZy3yeSYV4gL+AE66m+w1UM2L85FMQfYMSJ2qbvDFF53qKHHi9930Azm1Q/gDjNvP,iv:veuWXiIOvP6G4xgod+da4jP6626rS10JNW+tY8TYmnM=,tag:Yh/i304ai4VP9pcFCzrZtw==,type:str]
  otlp-token: ENC[AES256_GCM,data:go+CTAodlpnGbftXF/EqN+9d2SMaQuYPGczVH+sYvoNde2YB0xpbkH7tm57fIcxMPn7foPBCjyWO0bYxRzkPSLJy+RXWBnuXocgSAvNqTJYTtpoeWPJ4Jg==,iv:ZNV4+N6YifXQu3m1x1/3dY/zHsoSnZJxg1hpPC+DG0Y=,tag:UwUGTSkU3rvTKBbOcxv4hg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra2hwSFRXYTh2MjNsQzdw
        UWVTaUl4UjVvQjZnYllXbGIyYmFIZUxLbldzCnBnMkljYVVtaG5nRnA4Y2Z2VVlC
        TVJHbkZlTDFDVlhwd05oUnlGeDQ1dzgKLS0tIHV0Y1ErRTRTYVNiYzlGcnYydXpU
        cTVtcExsRFp1TWkvVzFPSzA1cGlOV3MK5+7ncRjUZJpztX+SzG3NTGjDmvVp5Abx
        ZAb3ahVEDiyOcn9CRAd5KAItcZ8LQOzVrriw/q0K6mpRK1cOrg+MNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ0tYc2dhQ0R6OW1SZjYv
        eldaRUI1bGN1ODBkWG1wNXVWUXFsZnZvaWtVCjJVZFhyT0lkcGdjdmxRRU1MMW85
        Y2d3M3VQU3dNcWM3NUh6UVpIMHhmUTAKLS0tIHNhSGJYZkVUWmxxWnIyU0NOVlJG
        UWxkbHJvYWxYUHMxMUFQRUVPRC9Jb28KwPsx+JISjM5FdQbGj391RBAj4gVSVLTh
        DgU6pIWyWYy2OSnV1zVnKYOHaWoTM3iFgE/yZ8Lt0ZImsWH6lSLY5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-30T01:40:31Z"
  mac: ENC[AES256_GCM,data:1x3w3B9qxkOi58hcTaDvHVOg9EEXF8K/hg/iZxnDGugOshElixtq9FOv5N5wpY+lL5lZJ0ohZNV/XtFTIKNXIh+xwbmzkOP695nw+beo9hSqyZRhLkeZGzx7PFRIhetCIHHbOS8NtpOMftC+wbbfo+AVcmBJgUpOzUbIQz0O85k=,iv:4igVRqiqvtc+5QMq/3mMeSrnaySOg+lbPQinQoT63L0=,tag:n73AUpDbZwxV6kfdW9c/SA==,type:str]
  version: 3.13.1
