apiVersion: v1
kind: Secret
metadata:
  name: discord-gateway-proxy
  namespace: discord-gateway-proxy
type: Opaque
data:
  bot-token: ENC[AES256_GCM,data:Vz7aDGPmeaDNGjkFUlzCcDIEzvsLBx4PYNxtV+Wz5YLGnquMEZDAkdmwsz8M0ebtsXCVk+xBhhYOfOMmhf5oqKKR0ZAZ0/Ts2x6fTKHU4he5crS9q+ObavdQ1jrVJbJC,iv:6uLmShqN6PWompHterpelu/RYZQmW80t7aS6Mp/yLYo=,tag:Pf9jZbKR4p4pTRprevar/Q==,type:str]
  otlp-token: ENC[AES256_GCM,data:go+CTAodlpnGbftXF/EqN+9d2SMaQuYPGczVH+sYvoNde2YB0xpbkH7tm57fIcxMPn7foPBCjyWO0bYxRzkPSLJy+RXWBnuXocgSAvNqTJYTtpoeWPJ4Jg==,iv:ZNV4+N6YifXQu3m1x1/3dY/zHsoSnZJxg1hpPC+DG0Y=,tag:UwUGTSkU3rvTKBbOcxv4hg==,type:str]
  pipeline-api-token: ENC[AES256_GCM,data:eMnArUJLkFzgynM86ji4a35AA6aU1z+xjkJsGc9mqwG+YVpOG3KHWe0oPuInSsIrcTlbD4H2J4aHKuE6o8yHOpdiUcNELxuA,iv:M9x1xb3GIetniH9mykbpDgRi5ek2shQwok+dQwKwh7g=,tag:L6VBL9dIdRhSHF4Sm91VDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRFNSUW1lc0FIeDA3NTR4
        UHI2TUcxeGxGL0xyODNPQ3pHc2VJMndzb0JFCldSSDF2T1RJQlp5dVZ1NkpkakVF
        WXdvUGFxM2RNMDZlNytCL0I2NEdxZm8KLS0tIFU5YzlZY1JHMFo0WEZuRjAyVjlh
        Zys1anpHRlE4eWZPb0dQcGc0SzNPY2sKOFf4Y9yePaoSJCt0qSokPSgPGcPxhGCf
        zt51QvdVRSjzRWSEZ7CSVUG0f0H7NjH2IfubuS//MNVKFsYJbFOqLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ3VDblpyY2ZGeks4Mlo0
        Zlp2VkRYQndYRzZpeFlLMmJacVJUUkp1UFM4ClNqN0Z2N0hMZTg4TlZJWEc2T1Fh
        Q0w3b1dOODVoSmVTT0JmdlVEQlF2VWMKLS0tIC9VUFNSczdCRHF4UkQ0a0FmNmRR
        R2hoZ2xXTU5NdG5BSjZKVkZwVEdrdTQKKF0V5oXqwwSD2DPyFIIq79RU1wP0dXks
        YqwK7SMt+5nHywqG0Gy4ouG66DgJ7zqEsFdrR0QfoK1e2hTJADnEhw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TnNDK0lmdGpjK2J3L1Bt
        QTRrcmx6NnpueGgzM1lEL0x3emtvNGtDTENZCks3SWNyMG1TVUFDbUhmRm51ZXpM
        bm9XakJuUW83ZVh3SnZ6R3ZEN0xUZ3cKLS0tIGFnRkUwNENUcU03dWVMRVlPTEVO
        REhDU1ZiTjAybVNqUW92YjhOYWFkS2sKINaoTYk5N1ZkyQnVpIKnJKby5nwsP6aK
        aUowgiZhiSeHTtc6ZDxpK6v1GKA9vyqndg052btZH7CKHzJBuThZdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T11:55:54Z"
  mac: ENC[AES256_GCM,data:3eulKEK+S2t+6ZZcvuUoyApUsf0Mc1udFMKgBuYRf7VwXPyftqMCi8BgoZ18gEzBYn/T68a39bqjOHf96ts/TPu+LobKz0MvNwGsjCux9YaLlQUaTzx+YHNoT6VG5vBVXGAM5UZOzRJCUUtyP/VbtD5ey3NUMeLBwjOT+B6jcNo=,iv:osRvdqbFFqS/DIqrIJmrRNMDyChlaqBp9av2XeP5IfM=,tag:DBaVG39iCg1AEDSQNqTCxQ==,type:str]
  version: 3.13.1
