apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 9router
  namespace: 9router
  labels:
    app.kubernetes.io/name: 9router
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
