apiVersion: v1
kind: Service
metadata:
  name: 9router
  namespace: 9router
  labels:
    app.kubernetes.io/name: 9router
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: 9router
  ports:
    - name: http
      port: 20128
      targetPort: 20128
      protocol: TCP
