apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - install.yaml
  - apps/
  - arc-helm-repository.yaml
patches:
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-notifications-cm.yaml
  - path: patches/argocd-repo-server-sops.yaml
  - patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-notifications-secret
      $patch: delete
