#!/usr/bin/env bash
#MISE description="Setup terraform prod environment"
#MISE dir="{{config_root}}/infra/env/prod"

set -euo pipefail

sops exec-env .env.sops.yaml 'terraform init'

sops exec-env .env.sops.yaml 'tflint --init'
