apiVersion: v1
kind: Secret
metadata:
  name: hermes-agent
  namespace: hermes-agent
type: Opaque
stringData:
  discord-bot-token: ENC[AES256_GCM,data:3OeWoJkanwwwJXDkbbgXriRJptzlnqrED5rPsT1MfM+LqkN5o2IOIPB02GcwtSBLTNl88xXcu++izaZvh3yk1rAxsu4spf8s,iv:n6ahJlu8ByDurQZa4GqOeO5MjZnYC1r8YAxqOc+syRg=,tag:0sNGs8tfgq+Qch4dfhfg7A==,type:str]
  api-server-key: ENC[AES256_GCM,data:UDt+mCwZlbCDDkvNe8z7TTO1vqo7XGVl7ASUl76dD5QVNeSK54AFIKJk29WCVwCMjFirUjhRF9TrbsUCDvlINQ==,iv:Gi/LbnoAuLjBhoO54TxMlSYSIU6lLbuCRq6+oVSt94Y=,tag:gbYiZXSiGifETvVJk26Nzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVzJSYXNhSFNteVlTZ1Jz
        UXVuTFFKSlN5dXJtRGNtQnpqQjFORzNiTlFnCjVsV1FsWVhFWmVkbmVuTzcwZith
        Q0ZCSThNbHpKZE5jMC84ZnpBd3hpZGMKLS0tIDhmODdmSlA3QWtGbDdBaFZTNHg5
        OWNyMGlMWUZEYUplM05PQ1lwcHRRSmcKci4ANzCwIC5n/xZCserhdWp3BVhza3U0
        A1X1MoFWaXp4qJCOUqyy+8GqsxemgGoiwxhMdcU67Rfah+hELmFVFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRlJRTDJkSzMvWUxBL2kz
        RGZZaVRueG5uM1dsNmxWdmxiQmtkZGE2ZFVjClpzaVhTcmg0VktyVC9ORnZIeG1y
        NHdESUJ4WU1ZclY2cXNHNGpBMHJ5bDgKLS0tIEFVM1U4cEprL3lDejhtYXdzUUpo
        RThxQ2VWTVlkdVMyejFycUZ1TlVSOEUKmlKYfxX1GloEG6md0LJcSkZzq5ooF2RS
        PUPA8XHzPgPGu316mX39k4HR8HdK+LWBA0oMFyF5UKjKm/P8Hx1pzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T12:15:10Z"
  mac: ENC[AES256_GCM,data:J36VI215YEffEoqv9gSzy5C/B8a5a2uR7KCnM/VpL01lC9BtijnOVvny2IA0e/yUEvNTX44KKIPAK9HoI2xeyLHNoHRiIzOlcrImeZjM+yM3eJ3pqvj7eazHE3xUJlCcYGolUM94Bkfr7djZsMPQCgUQ/lFZd/dqPzEWsm8PVCM=,iv:dRNWbOOf4+eu+yG/QxHWaZZbvWg8oMERipfU8ISGXPk=,tag:ur3MzMC9NK+OqSubPVYagQ==,type:str]
  version: 3.13.1
