apiVersion: v1
kind: Secret
metadata:
  name: hermes-agent
  namespace: hermes-agent
type: Opaque
stringData:
  discord-bot-token: ENC[AES256_GCM,data:3OeWoJkanwwwJXDkbbgXriRJptzlnqrED5rPsT1MfM+LqkN5o2IOIPB02GcwtSBLTNl88xXcu++izaZvh3yk1rAxsu4spf8s,iv:n6ahJlu8ByDurQZa4GqOeO5MjZnYC1r8YAxqOc+syRg=,tag:0sNGs8tfgq+Qch4dfhfg7A==,type:str]
  api-server-key: ENC[AES256_GCM,data:UDt+mCwZlbCDDkvNe8z7TTO1vqo7XGVl7ASUl76dD5QVNeSK54AFIKJk29WCVwCMjFirUjhRF9TrbsUCDvlINQ==,iv:Gi/LbnoAuLjBhoO54TxMlSYSIU6lLbuCRq6+oVSt94Y=,tag:gbYiZXSiGifETvVJk26Nzg==,type:str]
  dashboard-basic-auth-username: ENC[AES256_GCM,data:Qw7hQrnH2BE=,iv:iyjiErXtrEQcLWTv3ym0bZd6OXees/w7sLQB7XNzJOQ=,tag:H1WUgG7qprILS34IaFNZ6g==,type:str]
  dashboard-basic-auth-password: ENC[AES256_GCM,data:PUQsHi0wYIJtbxN1wqeXvEpAjJirYV9RjQcSF9wsUpc=,iv:2VwbUHOYZAZ/AR6605plB5HhpTOy/GJfNxGAQFIC/m8=,tag:HwgKuM4XgE/rQG7iPP+e5Q==,type:str]
  dashboard-basic-auth-secret: ENC[AES256_GCM,data:EFmj/XPuuTpHM1NH1TaT5TJVo5e4NP4YTMDQ2fAbQC1JWoB3H1ZV6v6yAO8=,iv:iHdjGGuPP36RZtd4fnoOve89p3YLtmTC5C2/Kfs1V/o=,tag:W3FikCUD0hXEBXDjOT0FUw==,type:str]
  telegram-bot-token: ENC[AES256_GCM,data:dc8o6Z7c9Yusc4pReDE5LfoOsMmlPbndvUMGGP0hxLdGDh7EmyLMZmmxPZ1nHQ==,iv:6HaDg6IfUqubIll81kKtdL8WlFOZGW3iUgRvvD9vQMA=,tag:F5CeawiidrfGUnk0Nuq25g==,type:str]
  github-token: ENC[AES256_GCM,data:d/aRHeKBMems7R6uJHIbbivGJby3y01dda6EbQoiFl0jAtKbFL/+qw==,iv:yoGBvGTwHsKDJ7ZbnVGy3lFzTMAceMqQhoA6XZbUMUo=,tag:wJzPTsXVxssA8FGoJviZnA==,type:str]
  mcp-context7-api-key: ENC[AES256_GCM,data:sMD9UDa9uzxX0DUc9KoeAg1UevNoU2beYFa20fLP9qCLYs7ou64Gea0qxQ==,iv:hGh9XHIwZ01OOxUdDJzAxafH7RGYtRSiKtN7o9uOfSo=,tag:MRl4SzNCN0QQqi8amnmy4g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVzJSYXNhSFNteVlTZ1Jz
        UXVuTFFKSlN5dXJtRGNtQnpqQjFORzNiTlFnCjVsV1FsWVhFWmVkbmVuTzcwZith
        Q0ZCSThNbHpKZE5jMC84ZnpBd3hpZGMKLS0tIDhmODdmSlA3QWtGbDdBaFZTNHg5
        OWNyMGlMWUZEYUplM05PQ1lwcHRRSmcKci4ANzCwIC5n/xZCserhdWp3BVhza3U0
        A1X1MoFWaXp4qJCOUqyy+8GqsxemgGoiwxhMdcU67Rfah+hELmFVFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRlJRTDJkSzMvWUxBL2kz
        RGZZaVRueG5uM1dsNmxWdmxiQmtkZGE2ZFVjClpzaVhTcmg0VktyVC9ORnZIeG1y
        NHdESUJ4WU1ZclY2cXNHNGpBMHJ5bDgKLS0tIEFVM1U4cEprL3lDejhtYXdzUUpo
        RThxQ2VWTVlkdVMyejFycUZ1TlVSOEUKmlKYfxX1GloEG6md0LJcSkZzq5ooF2RS
        PUPA8XHzPgPGu316mX39k4HR8HdK+LWBA0oMFyF5UKjKm/P8Hx1pzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-06T09:14:29Z"
  mac: ENC[AES256_GCM,data:5ndK/7rd5+MRnLrPPrOBUonOf/B4wVx103eu1hmWSOK4Ozbl77ajEFoM3h9oWoD4QjYbuaVZOvtZaAhaX0BgHbGQZnSDGNUbf34sVthYaD4ypQzr1Al4JIJFsR9K8vuAYJ+t0i4rLim0CqCOTl4o5E5flYd776fyQYLrG5IUEFA=,iv:kbkLSKHXo9k5mf7g9KqWGaqYsb4XUF7dQwPjTsqYuXg=,tag:kkJ4K1aUC37tV/4iTCYWHA==,type:str]
  version: 3.13.1
