apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
type: Opaque
stringData:
  webhook-url: ENC[AES256_GCM,data:um+fXY0WOUGMFjC4zNrr9Q4RMXkOjO32GaOYds/8BeyqY85pkf+uHWpq6WUlw0z4O6O4QtQWB2nSIaG1DRyvTYF+pQG0SkOdv+AeZkI1PboyYra5ZuHDvRuaRAM4FnsGrRwflXMF8efmR/H3eqUe1glFLVnRsZci4A==,iv:h0n6a4saZzM9PbaVEZkhjE1blRAjoTKkyzUVIYQVCU4=,tag:XvCD3g//PorgMZ6cG9B6qg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU3NSZG9kOE03YkRTYVdO
        OHF1azZUODJ0UFp0Szc1QlBmRUJBQk9oaXdzCndPbFZDRVIxcXRhK0lEZWpMUFB6
        RDZabkliR2d0Q1BOQWYrL3JEV0kzVVUKLS0tIHZIRkxwN05PRERZK1VmQUpQeDBn
        YmFqRmFzQy91enpHTW5lSmVUclc2NFEKPQfAzz3jazLg2+1XlHHWR3qC6hk8gGJA
        71ou4UlH8Ocn6k6Bnhsfs1CNuraqt5LvJs3tEJpJNKI1aiDaJdgCoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aXJYZ0RoZy8rVFhsN3ZY
        NUpWVnplVmMzcXk0NEdBUVVYU2NTU3FlUEZBCk9JbXo0RWlDVVNIME1yNWw2d2F4
        OTJVTUlaQUtGOVhFc3NzOFcrL0dQdXcKLS0tIHBWK1FHRmoxUVVVOE1ZeklxaXpr
        bjkxam5SeUYrNUdxTjFLNWxjRm5jMncKwYBcLuRtam5hAgEVROrfts/MMA4i30MN
        V5qQs5S9QG3dRufc/cTqN1M5MRKQxPvUYT42FCFjSnV6rPxcOogtIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodXJzRzVQbStXK0RmbmVp
        ODM3TVZtNy9hQzhlV0UvRVI1L09ydlJ6OXhRCm5DZFppSDZ0R2FxZDBRa01rUjNh
        bmY2STc5SVB6S2ZSOXBxa3pzNnpMQXcKLS0tIFJWdTNTT1lJc1Q4M21zdFVzZkg5
        U1FnWTVSUWNpRTczN0VQeGZiaUdNcWcKvELHp4FYA0LCnu3AiLctSNSg7PDlyedd
        ymeNwuIcgyP+CWtao9YoCD0st2XG/KqrYuKPpMmVO3vUM6Fkm62X2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T09:31:49Z"
  mac: ENC[AES256_GCM,data:QAoz1IpUxrVkHEceEuqfNXcTXsRptxLgJasCsTAovCTXHgzx9YqjPnmnu2+NHMbmkYH4UOrqP2200r8DSRdRU4MgYax96hKYcNexx+b7wfpkMPqjK0KwDNROsRKemMq8cbPUYxNzzTpkhkqI2xFjsCYyVgt3odCTnpC3QAFIosc=,iv:OF0fFJI+6bfOVjEs5B89dw7cKHGK7UCLr636HtBcrl0=,tag:WR/mHwcXsD/mH7xZVRF8tA==,type:str]
  version: 3.13.2
