apiVersion: v1
kind: Secret
metadata:
  name: cf-workers-otlp-token
  namespace: monitoring
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:LHS90KWat080Xc7Xd0DXlqgcXnMc89gjjJ7e4yuIMg/cEI28CsxadWI1BV/HVZndzMSk9dC3e9Pf/tlzxznFQA==,iv:Biw+JfiV7OSve1rlxbvMeRtAHO+ZCZTWolxaR6lyWGI=,tag:ZfnSy6TNqJ4SN8dsmEQe3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaVF6cVJHTG10MnR6T3ZG
        cUhtT2dPNGpMRjlaSmhxZnRJWEJqbzhmZHdZClRFQzlNcmNXdFlrY2puMVlxeXNu
        UXVYR2M3cC9kNkN0Nm5sN2hWU3Q1NGcKLS0tIEZzRzViZGI2UUF3bStSSWJ4VG5V
        MDI0Q0dlWHI5UUV0d1U1dTFZSVNSdVUKLzK2gHibtT3zkczgWzoDr8rAFUFzUKHA
        L8qoIAHtmuIYV34gh0hz8Z4M5i4zRIk2E0kfshhKDuxC5F7kKV5pFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWdLa29UdTZIZDZudVZP
        NkZ1SlFuU3hGZU5qeEU3NzVHdUx2ajhEYjBBCjJld2JWdlhzQk42ZUM2VWtyZFFG
        Q3FaY3V5Q1ZLbjlEc2JwRWNvTnZRaEEKLS0tIHJvU0t3d2owMEhUUlhtc1E1allO
        MmtoeGJpZnlyU2t2KzRvNHJlZ0M3RVkKfqGsGHdHFUmwGrO50/9D2bh/k1Bald0f
        bh4DhYgxtRzpB/MgxzW/zWguvX41xnOa/yXTOpaETmTomFpbE3k5AA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbTBMYlliY2JMTllLR2cz
        cDhjMFQ3L0tha1pLOUhKdVBKRVFUcXVGckhnCmFXZm9PVHFSSUpJeTZKVVdlcHlq
        MGtGbk9CaFg2SG9qWEdaSTlEL3dsbnMKLS0tIFg3YkFMeGFVaTA4NUFJKzJxWElF
        RDlQTUxGWkFRUjJLbFhKTHN6aXB5TVkKxRuhMqIJhFuqlVKqMj/W0rEr83VDsIqy
        v7y5b1G0krICJcjGt5iJZrToz6+C9kBz+cd84cbPNt3ubvOARpWT5g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-29T06:01:08Z"
  mac: ENC[AES256_GCM,data:cARKMBBtcheUSRLCBKtlRmum2bzMHfsFZ8FbF0UHPe6e+iaUHb9g13EAvC/5QjGi4tVxWiLtGJtNciBnptruJmtxHuy4/v1jZiUmR3kXuRXsN2VR+LR3nFsPHHSzDxitvZpNXbRGKr9EwK1hLFwGCOt2puZci5tutUeGyGahVsw=,iv:oWuKmMMoNwNqpn1hfEKlH7wyzfel9mtKiSrfjiexzH8=,tag:b39xLms3PTOLMBv3SlcmkQ==,type:str]
  version: 3.13.1
