apiVersion: v1
kind: Secret
metadata:
  name: grafana-object-storage
  namespace: monitoring
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zlAo3VXNJ1+8BQ+2p32zLcWNwKqfv9+C0Q6BZDtVIJI=,iv:I0GtgMoeGuP2AJ6j52maAHiLtVsgeos2l5FNZx/FGeg=,tag:AJaR01IFuJPPbt6+64gtOQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2sEJWW3VcTZLT3HEj2HW6aOzsOvIkoh22lqvmWL9lX3qD9LA+esnENTwNpkPCKivrPXVQ6s+meU1vW3k/leI+A==,iv:xaIucUD+gDWGLnUkjBMhC/NeCzilIqsO35yQnWwc3Ic=,tag:tWV20T+1H3oTixr70cdX6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQmk3cUtmNWF5ZEp5Nkgy
        dktDTFpiaE9ja1dOSHkzSW1kd0NXOXFtSWpNCk8vbFQrY25VeW8yeThSWng0Y0gx
        U1R0L1NsTm5NZHJNM0Zhc1VPMjl6YW8KLS0tIGZ5RzdXK2FyWWtMUWxiTFZzOEZR
        RFlVK2ppY3FVVVZLQ0dCdHRaV3lieGsKwIDVSJrG1vbXlIgiREkqDBNJMYIUxfK3
        MjOV+1Tx1FiOu/WvYMe/x496biqIYyRwp5XgSgMmJBEOLG00LtQJ6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RFFEaURwN21OcGlidHRO
        UXlvaVIzcHZYOWIzczMwZkU1M1NybXY5cjJnCi9LbVZzRFQ1VzF0Sks2cVF6YnVQ
        MXZxemRBOGJjUUJERS9PSi9QZDcyN0kKLS0tIDBObHZOd3h1UnlzdEtIaytNY3JM
        dU5VTkdsNnZIY3JCek9kQjladHdVNkUKGbUx5tMsHQv0UBbGP3NobuGIAV/o+aDO
        ux9vhBmbeAcBHlRCTr/kMYNnZKlwdI5nWsaHRo7vUvfjhqyapZVsUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK1F5QnZZdFpNQ2prMllB
        OVpOWnVHU2dWTnJIOFVoTDJ5MVZqTmJYUFJBClphSGl3Ui9nZS9tSUt3ZHJqYVZm
        TStxU2JMVldvQTd0RDEyUU1OTkFMdE0KLS0tIDhyc3VoODVua0FnNG13WEpTZnRO
        cktpN3ovMURwOWZjejd5aEs1aHZwTlEKcRObSbQ7JJtMtK/15M0GwQbH9sIMK5nD
        G+5wTJ3GLNrPv2S0Wu0whEO4nS0wvRLtl8kuih8AWXcgJkwJ2LnDow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T11:17:16Z"
  mac: ENC[AES256_GCM,data:84akGPuay+cv4IcWsP0eJHSgPUs5HxkXV0WKG3I6y+IDs/1QNcsrewqV1sV6VrArwLsqRPG1sDsyNvoMh1Gje+1KSevjeBhc68Rvt0sZ3+Jcckejk5MWZ67eOXM+GMxHn43SAPF6xkBrSQjuCEf5MT8t8lvjMCChtph9/QdYDf0=,iv:Hl/9MnZ6pH/8xyfLzYrbpP70RTqPxahZ+OULlVafZUQ=,tag:5UC0+gY/wLdPnqBcxKvoDw==,type:str]
  version: 3.13.1
