apiVersion: v1
kind: Secret
metadata:
  name: grafana-object-storage
  namespace: monitoring
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zlAo3VXNJ1+8BQ+2p32zLcWNwKqfv9+C0Q6BZDtVIJI=,iv:I0GtgMoeGuP2AJ6j52maAHiLtVsgeos2l5FNZx/FGeg=,tag:AJaR01IFuJPPbt6+64gtOQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2sEJWW3VcTZLT3HEj2HW6aOzsOvIkoh22lqvmWL9lX3qD9LA+esnENTwNpkPCKivrPXVQ6s+meU1vW3k/leI+A==,iv:xaIucUD+gDWGLnUkjBMhC/NeCzilIqsO35yQnWwc3Ic=,tag:tWV20T+1H3oTixr70cdX6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM3I5UTV5alg1M0tLeEZS
        UDRhVVFyU2tNVVF6ajgwYkZkUFZab3pDOENVCktTSlhwanBCaVRiOTEzWGFWbk1H
        U05JTy9jTE9VQTluSWRiQmpyeURMYUkKLS0tIGpnS0N1MW5qZy96N2pOUkVEMFdL
        RFlXOTY3VW1GOXVkTnRFQm93S2diSUEK+mIZhplGvTuNdyr8B/o8NSax25ghDwGB
        v4tOJbjso+nSyyfa+kgqlWJ0+yMPSVMlO54MmleVpI3gvw9t3Qj1qg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcWZWZjJhUHozTjNvYzlp
        czBoVUlhZ1VQUE5ISGFzUXhwSHJUZUVKeUdvCkFjMFRvMURRWDZJT2pNRkhqbWhr
        V3M0OVZQcEE1RkdTWWdpOXlvSzIvb0UKLS0tIGNTbElUTG9VZjRRdmZoc3V3Q3VB
        ZlU3K0RlOURhck90dk5iVGhNd08wS3MKtppYAbxnLgfED/r0SFBfjPdm759ehTsl
        Kn+SSYiUyUStE472K37BnLpnbEi+HCkPn+824VTK6jakDQssW8eHoQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T11:17:16Z"
  mac: ENC[AES256_GCM,data:84akGPuay+cv4IcWsP0eJHSgPUs5HxkXV0WKG3I6y+IDs/1QNcsrewqV1sV6VrArwLsqRPG1sDsyNvoMh1Gje+1KSevjeBhc68Rvt0sZ3+Jcckejk5MWZ67eOXM+GMxHn43SAPF6xkBrSQjuCEf5MT8t8lvjMCChtph9/QdYDf0=,iv:Hl/9MnZ6pH/8xyfLzYrbpP70RTqPxahZ+OULlVafZUQ=,tag:5UC0+gY/wLdPnqBcxKvoDw==,type:str]
  version: 3.13.1
