apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:0KyJxSs4+jg=,iv:YYpOAZt0SHY0qyULvpjdepHH45mYGtecx/MymI2XEYo=,tag:jey9XnTWySj97xJgvLIIBQ==,type:str]
  admin-user: ENC[AES256_GCM,data:jSdWXyI=,iv:FUz8MnCt81sP/h6qz3sothQ1Rw96WPyCCEhbR3GNUFA=,tag:McPetgT/4swZMdtZWHF00w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ2JVVFJjSXVSQnZXeTVy
        aDVmYkREUmpyVDcyaFBWVDBvbWd4Y3A1TlZFCjVmSk5lYzZkci9BVDRFR1JWSWl4
        dUVzMTBpMnhRdkR2djRHUFVlOWFDZHMKLS0tIDRrd0VQV0hIVmZDNldVVTkxUSsy
        VXg3T0tmS1F5Sm9NVEJndE0zRVA0ajAKGMc9arfW8lkydSQ4/5cQ+Mi7K3Dag1IC
        YVrNKWChiaHYrUmiCMrYO2+fzy5klz4ZKm6Dq4JP4z21h6YBAENLvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWDJYb1JHcklCLzQwY0Vo
        YlM5T2VtbjJYa2dSa2V4KzZvK0FwbnB6SVJJClJ0Ynk4TThvaVkxa3J3TUFwSnZu
        eU5SWTZ0dUxTNkp0TStGNkwySm5Ka1UKLS0tIGorTXc1N3RRYnBTN0J1aTdrS013
        cmpFaTlzRGl4OUVKaG5odlc1SnVwR00KVQ9BSpbKyHHV0HXI6SBRlI5arj9cOA2Y
        OScPxriE121CGEU4hpfPTXR0iEQTW08RVmhp6hJbtaGQPa4Sa6jQaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T11:16:37Z"
  mac: ENC[AES256_GCM,data:9N+o05HGYg1pqG4jTjFlWYLBfHNQdIrv9yECwk8vrHJPaZXb380iGnv4AoQ5L7LWvlOMW2NyMSK9r8k2T9lFHRyM/X9sOL1LSO0016s6DXBC+LYoaQdsK1zBIX0ZQyNjqhKYE4Qd+iC6nd6fsV140gHC7hcisTwa2QLQrKjMyFA=,iv:tEN9rpECyUDsfrzAsoE8ai43xBwqhoYEf4VJem+OqmA=,tag:bEhfZmncyFzbasqGxK1qXA==,type:str]
  version: 3.13.1
