apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-password: ENC[AES256_GCM,data:0KyJxSs4+jg=,iv:YYpOAZt0SHY0qyULvpjdepHH45mYGtecx/MymI2XEYo=,tag:jey9XnTWySj97xJgvLIIBQ==,type:str]
  admin-user: ENC[AES256_GCM,data:jSdWXyI=,iv:FUz8MnCt81sP/h6qz3sothQ1Rw96WPyCCEhbR3GNUFA=,tag:McPetgT/4swZMdtZWHF00w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTDNjRFhRLzRGemxaNjhS
        aEU3YndrZTV5dE5xUVpSZG03NjFIQjFpM2w0Ck5SM01zUitSMklVVUhWU3BQbHFo
        emtZTk5nYzFzVmlURzh1TTRkNDJCRlEKLS0tIEVxL3RSUENZc2ZPTTg0eTdXc01I
        VWNxWGhRTXJ2OThrLy9MWDgyeHZvT3MKzQsr+v5SIANVc1uiJkEr/y3gte/igZz0
        AAfl8Db+AxUp3J5KxuGDVRq0cMqZ6+BCAe3dRkrFcsFhXBSex6LHTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dkRoMXRYbDErQVM4c1Rp
        cWN5aXdhN25kSk4wMnZac1hCM2ZJa2JWaHlZCk5VT2hXSEFuU3lzSXlWOWZIcUpG
        aWtObThGNG1KN1ZXTE9IN3RCUExZNmcKLS0tIEtHbFdCNExaZUtYN2VYa2p5NjZl
        SWlJajhPV09Pem1iMHlKMndRa2tncncKA3R4h5ngLohi/AD4fgfTVRS4WPddadP2
        Rn1kVIo7WKPImZmxxFxsj3MZqlUObD9pzYqWK/6PeYde927Te7O3zg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM2lOa1pYTkpEcHBNL1hE
        dGNmQy9JY0JxZzI0N0hOeEpVVzUxeHY0UVJBCnYveW41VzFIUVJsdXhEUkU3WDVw
        QTM3MWdCUTZjQnFxaDlDU3dMVGlHelUKLS0tIFhjWmc1bXVRbkFrekszYXdkKzVN
        NjZydlZTQnQzcHdyRThKVERjWmplTDgKWCmrNccSr3Mrq4OooH7Ykw2LbeK3Gpxn
        +Vw1XnezsiA89mK3ijp29s/Bp1s2tCGIgJdIYhC9BbAJjveis9z0gQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T11:16:37Z"
  mac: ENC[AES256_GCM,data:9N+o05HGYg1pqG4jTjFlWYLBfHNQdIrv9yECwk8vrHJPaZXb380iGnv4AoQ5L7LWvlOMW2NyMSK9r8k2T9lFHRyM/X9sOL1LSO0016s6DXBC+LYoaQdsK1zBIX0ZQyNjqhKYE4Qd+iC6nd6fsV140gHC7hcisTwa2QLQrKjMyFA=,iv:tEN9rpECyUDsfrzAsoE8ai43xBwqhoYEf4VJem+OqmA=,tag:bEhfZmncyFzbasqGxK1qXA==,type:str]
  version: 3.13.1
