apiVersion: v1
kind: Secret
metadata:
  name: dev-pod
  namespace: dev-pod
type: Opaque
stringData:
  app-id: ENC[AES256_GCM,data:QEI+CYDdQOejhfuBS1AaiQus,iv:vFm5f1SpPLqUAJpm8XEk/ufA9R0OOfHI8+R52PHl7ws=,tag:t59XZclT+sElcX0tqMM0Xw==,type:str]
  installation-id-tsar-org: ENC[AES256_GCM,data:bvzUPMa37ccKpOoBjwDzTfYhhvCCHqWJssjb1Dw=,iv:rcKXYn4PXsXmHyQfkv8llXSXLi0Delv7BMyZ///zxOM=,tag:05jHRGANUhvnyc5YLHhoHg==,type:str]
  installation-id-taiki-kuraishi: ENC[AES256_GCM,data:hecvlCktdMHipI6P64lF5C8c7/xXXy4OjubuiDwk5nU68Oo=,iv:Vu4AwrIxw0hAWU/SYUTnOQWymh/Mta5ap4z7Km3jTso=,tag:BTWEpuOj3wKO3e07h7ar9w==,type:str]
  private-key.pem: ENC[AES256_GCM,data:vxYC7SvKc+oFvg9HDrCTL7wNINdzzzaGVNyb9PLbqA==,iv:EcsYWG8hBED0RysysWDLZE9lFd8Nibdp3uRa7sYszbg=,tag:xdLKKAFkp0xmf1Hn0Qt1Aw==,type:str]
  ssh_host_ed25519_key: ENC[AES256_GCM,data:j8DEP1dtmQ7byodPfCJVaSOz7HGuaF8HYelZBrnUzglYqLKZqKZwIdEBTLMs3doZ4ED971+4/3yRIypF1sfT/rgom8k9LWqeU6YgcMOJNmQxzwaetHd7FFwBH+xJF/iK9loDWsSYy0UtT3FQ4Flj39m8cGeALjeYSmaeS3eFHn4/BrGWt1r/Oh94HKHNCvhjNUmanmEDDki17RQUtI4HNrDBjQynkdMwa7oVjSghYVkOxonlhXft9OhcLBU78QWOJXGAjaXzUdMdmKwrEQkafieSld1HbsYWA0ALzjZAWh3ZH5U9qHqJs+EZ/4TuiOIRVjjn8kw4r18SfUAQhs2KpZK6UD9TYgkemglb6P2djGM8xbrcnimn4Tm+5DVr2xtVD5DImVp0WTQXnWZidoQg/JoGfalWn44ggvvYSHUzXdsZUJGiznwrjEcBDMQ0zbOrqstSlPsAXoXAO5B9AvmA9WLuJTaYCLitojJAVHXmCEDhyc/4ajUQDAygBq30QrFb43+UaY5voShQiTm8SNuhz87/+7B9LaASzzhF,iv:97QaOF2ZL+ocJwmhIWgVQkPu6+8Y+YUIhfZNXEiR18M=,tag:w/LmIrleKR+eMYZYTSPOsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbE96VStrdUFXSHRZelJY
        dXBlYjh4T3pLS3ZhdzFBRU54MTlJZzIyZDBzCmRka2tRdHNoSHNjeGVJbnhhcTRz
        VkR3SmcxMVUrdDJQVUlzT1psMG9oOWMKLS0tIHdJR2k1YkpBTmpOYzJtRDhNRmda
        UHVHRTljLzlPczdsREhOaWVrUDhWZ3MKM8VtdZ+t3jR+Nokzxoz8ws5h23Nh1vRy
        Leb9aL0zitc9m9YlqrH7EVRX0xZJfGRoWWuKD6WXKniMpVkpM3MnGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVHJ0a2R6cjdWMVNFZnBV
        YkJ0TlJ6TThuSmxvY3VDY01CYVF6Y1RzUVJvCmdIMDlJM2h1ZmVRMzhYRGJXRjhi
        SkhmMWVZQXMrVVJMTFpwbko4OGQ2QncKLS0tIDRNTlNhdGZ1endxeGdxSHNNU2di
        T3gwYTJyeFBoc0U3MG5DUGNtVTd4TncKDm6pv3ULEe5w3ZX89vJUbw/Loxtz+JTT
        4mDd0Gd2xsvUy5FIF9bBWvC1gsop5P7ouV3u4e9vclo150D8pnUjuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T09:25:14Z"
  mac: ENC[AES256_GCM,data:Wm/vEwpKf/NzXRbd7doZNp1hr1Tpi8OTqYAItY/svyi4Zhb9MusohgBd/6WLsFc9tO821oZtxwawBAROPxX2BqTRd5gNfbqjaROB5z+poORKBnm8EE23XeT6QXdw93wMdWx5yTrIBUqxslBjLEch5eRkSsZHKg5flqLPdaM08p8=,iv:Crn2uiQFn02kyj3fVdmE/YRGkGiIthocu/wZzfebrhw=,tag:z+SLHcReJbSaTlQ+71uJEQ==,type:str]
  version: 3.13.1
