apiVersion: v1
kind: Secret
metadata:
  name: dev-pod
  namespace: dev-pod
type: Opaque
stringData:
  app-id: ENC[AES256_GCM,data:QEI+CYDdQOejhfuBS1AaiQus,iv:vFm5f1SpPLqUAJpm8XEk/ufA9R0OOfHI8+R52PHl7ws=,tag:t59XZclT+sElcX0tqMM0Xw==,type:str]
  installation-id-tsar-org: ENC[AES256_GCM,data:bvzUPMa37ccKpOoBjwDzTfYhhvCCHqWJssjb1Dw=,iv:rcKXYn4PXsXmHyQfkv8llXSXLi0Delv7BMyZ///zxOM=,tag:05jHRGANUhvnyc5YLHhoHg==,type:str]
  installation-id-taiki-kuraishi: ENC[AES256_GCM,data:hecvlCktdMHipI6P64lF5C8c7/xXXy4OjubuiDwk5nU68Oo=,iv:Vu4AwrIxw0hAWU/SYUTnOQWymh/Mta5ap4z7Km3jTso=,tag:BTWEpuOj3wKO3e07h7ar9w==,type:str]
  private-key.pem: ENC[AES256_GCM,data:vxYC7SvKc+oFvg9HDrCTL7wNINdzzzaGVNyb9PLbqA==,iv:EcsYWG8hBED0RysysWDLZE9lFd8Nibdp3uRa7sYszbg=,tag:xdLKKAFkp0xmf1Hn0Qt1Aw==,type:str]
  ssh_host_ed25519_key: ENC[AES256_GCM,data:j8DEP1dtmQ7byodPfCJVaSOz7HGuaF8HYelZBrnUzglYqLKZqKZwIdEBTLMs3doZ4ED971+4/3yRIypF1sfT/rgom8k9LWqeU6YgcMOJNmQxzwaetHd7FFwBH+xJF/iK9loDWsSYy0UtT3FQ4Flj39m8cGeALjeYSmaeS3eFHn4/BrGWt1r/Oh94HKHNCvhjNUmanmEDDki17RQUtI4HNrDBjQynkdMwa7oVjSghYVkOxonlhXft9OhcLBU78QWOJXGAjaXzUdMdmKwrEQkafieSld1HbsYWA0ALzjZAWh3ZH5U9qHqJs+EZ/4TuiOIRVjjn8kw4r18SfUAQhs2KpZK6UD9TYgkemglb6P2djGM8xbrcnimn4Tm+5DVr2xtVD5DImVp0WTQXnWZidoQg/JoGfalWn44ggvvYSHUzXdsZUJGiznwrjEcBDMQ0zbOrqstSlPsAXoXAO5B9AvmA9WLuJTaYCLitojJAVHXmCEDhyc/4ajUQDAygBq30QrFb43+UaY5voShQiTm8SNuhz87/+7B9LaASzzhF,iv:97QaOF2ZL+ocJwmhIWgVQkPu6+8Y+YUIhfZNXEiR18M=,tag:w/LmIrleKR+eMYZYTSPOsQ==,type:str]
  user-password-hash: ENC[AES256_GCM,data:jVt4ZUW9gXzSBC/YhMYVHQTAsZxb+sq2UQ7/V3u6u8Z+W9ulle9DyjBg9aJbbXMX/YYaiq2qRPNz1+n3zrYYih9BLJRdz5w38sd952yM62ww9epqqV9eSYqo7qc5tF0yQ2J0VKvudzl5Jg==,iv:0Ra9SZz/Y0sswjTYhJ+MYAKTjsV0FdZX58JBYkQOHe0=,tag:+m8KBMjkroVMP6yUk5wLcQ==,type:str]
  sops-age-key: ENC[AES256_GCM,data:TVjC6boI3+KmEw83h17l2Ptvz27aCEh5wdzOD3RLdIewWAPD8DQiJbx/6abKzvK7azfftessE6cDyvPWY3nFZzHWCp/sn4I35Rk=,iv:u8Vvthk5TsjgILbhLCh/+m5lxU23BoNXj2w5WCWEFxo=,tag:JXu1uAfbxHKJ/EQNXDEU7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdkRpMXozak1mT0ZnR2dW
        UWYrTlNqODJEMjVPUlRKbWVKenJQZ1ZWY0VvCkFwUW03NHZGb3RZQVdhc1AwcVlS
        VXZWOFBwNWYxYUhSMU9SUEg3ZnFGVUUKLS0tIE9uc1lSRThZN2lBMUs1SXM2VUNO
        d3AzdE1iN3V1MEN6UHh1V2JkWTFSMlEKw7Mlg6o0SefWOqBTOgzzxGTx07G+dz8F
        coNn0ioEMzFj3TFn1hM57tE9czp11P55dtv9N9tNQQWvZjnVNapVeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOGlWbWQwdDZGMEpoZis3
        bVhraXpxaThMZTRSRkNOaUlkYnJCdmxvZzFZCmRNQTBWS3hhaXhzMk02MDdTYzBh
        NmxicVdHL1RRQUY3YVBJbmoyYTFyZTgKLS0tIDVEaWhsN25COW1yMm52SkpXSWNt
        TlQ5Nkc5ZlBVWUFGZnlDcjJlWVVMU1EKTPp8d1tEkPotWsZ0ge7sBcAODDEAZx9A
        I4BbQbYVbImr9WuAucH3ypxuFWcwloA5Hkx7m2TnsB+CZPyNh+pwMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VEJMSlpKZVdrZHV5a2Zn
        SHJCR3puV21TWm95bTRSSE11V2hpTHlqS0NFCjlMVy9jZmVsQWVaZnpxbTFnd0FC
        dGxFblJZeDdSNS9GSkJ1bVkrZHp4ZzAKLS0tIGd5Q1VOWHJ1OEpINjdDeEZmc2Fp
        OURwUXMyeCt5OW8xc2cvclJBQlh6WWMKq6qR935zptdnKwMvLhzbD3R6j8Qzo2bc
        f7TAtaggEFCZ2AeyfEFMth8mynlPiSUSMxtiRVAVYSq8J9gY41IXyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-10T07:50:11Z"
  mac: ENC[AES256_GCM,data:+6TQpV+/DJolHYGGne4naNVibQ0nMwnGkN1oWae1ASFkXvo8qZEPdnx5slgG1GypNdGPsmFtPQT1o2pfY16gr199HfsD8FUpLKda0JrekVK4GeTSxXeCFL915eZpUBLopnD6ELLGu9crhRXaul1L5qNieWc3Gf3cnowkuLe3fCg=,iv:BNqaHTVxr1L7APKUs3Bc9NC1YSA2wDz4S8Bbz4PKv6o=,tag:MRM8plGhNd5sK0HuIlZJDA==,type:str]
  version: 3.13.1
