apiVersion: v1
kind: Secret
metadata:
  name: dev-pod
  namespace: dev-pod
type: Opaque
stringData:
  app-id: ENC[AES256_GCM,data:OXs4b7810lu3jEpMi6OMgNnQ,iv:qayZbFeaahLCb+gAPggHpc95oo737+ad61R9ixyj1Nw=,tag:a5SQtRIJPuDDKEMtA1GwvQ==,type:str]
  installation-id-tsar-org: ENC[AES256_GCM,data:pjYbopTNPPjA4T+mKC4NXF0p60G0duLVStYTy5M=,iv:dGP7W6vj5Rv0kchqqHMRZB2P/tCyHhLvMaFNYcgMEok=,tag:YjoaoWJPpjuGAk6w8M3N2w==,type:str]
  installation-id-taiki-kuraishi: ENC[AES256_GCM,data:1M8C9FMVUCjsROMUrwDSwJghOgKAFxLpgSh06Po+fd7+wo8=,iv:Tmc7bh3crD3sN+FqZ0Mbin/Exs6pZFAjc13axiUro0w=,tag:aSkcaIS6ooQrez1qjOu6/A==,type:str]
  private-key.pem: ENC[AES256_GCM,data:QWD+gsyRijfoQ9YM1g2xNQPqVyM2kewen6miPYOQMg==,iv:O9LEOfnfMwudpP1PsZDuVNnOO8ZwBc6q6v5gXg5cKA0=,tag:SjSV/dBJlylDwaoFLhqzHg==,type:str]
  ssh_host_ed25519_key: ENC[AES256_GCM,data:5WAvNYda8Srg7BPYH9OgkbtxdVAYu6eoZOyzs9uWehbqGC5jrXXbi7xZ/Egw6D7NXVDIa1kXuchkNFq0Cd/QVkMnNck4WNPozFrliMV9lumekTdwtlmACNx6Bul7ZwOWAbkqkixVJABbMTCwZ/QFQ/Egy7jpJrT6XNzsj8IJQz6PlmFKJNAfOVCbacVy12PfGzMVTK3tAdesWdOYYbz+UpvPFxNXyEzYY3N8m7gc+NIidTl9uQPLv55oGnZ42mlM/N3i5565FE65wXKp1Piz1OqScx7CQmwqCYunak4CRKIVLdZJsK4Mmk8jlwaYfH6L9KacxG8DSC6KYdGYWa7db42VKdo5C8aTdMrjUTENOZXhW7oWyoKC3VEMgy1RaMIvfLyLn/wwTaLJnE2k191LoI4NdC28o2BGoJqajkMXoxB3n7YRUO06GSdt/qihI1XRn/b6nipCAZjh77BOX6IKtD3a8r9WXfm2lfskHrGTjEwWVtqemA36LEy28mnS7IRjLmFMFoxS4L66R4BM+UyubNaIu0tAFXrIa5mC,iv:NroDlSjNctf/JnWB2dHSDUrHjlDp6tZ6TxAlf1ThO24=,tag:v+GpbmdkgMFUIW/llbCZLQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXl5WXJWQUNhS280VVdv
        NFl2VEZiQ0VQOU1TWnhudTdPamtPTWgvRVV3CkNpSTEwVlQ4d04rMzZjaU5Qazk1
        MUpYUzRZUUd6VEdqSjFCMWxyK1lCTFkKLS0tIERpbnVhUnZPdjFOMWRIMXpZdXlP
        Mmd1aWZLZFRVWTk4aWxwNDdnVnhURncKIwBPzEKg/JgoJwcTV5pAaS1xwETB89kF
        elkvge5SJVKHQ/SVt5tSyjAtM7j72uU3AtieCUncT9O0ZnkMLCxWPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L2VwNVZSRlNlTXdRVUNi
        WmlPakpwTjcrRllUTlZvd00xVHVUM1JhWVE0Ci8rclFyRWJyQjFGUEE5UXdBSUVm
        WGZ4akVvNStudWo5bDE4bHlsWGJuZ2MKLS0tIDhITUNDcHVkay85Zy9mMkdYbktE
        T2QvKzJrZWIxdEZjSU5nS3NnTGwzb1kKH7mGpJVP+sTQaZ6FoGcKjI0buRUTawjM
        jgQcMfpGjVtAe+6LOC7Q8ZfsiYnuD8rJ/Z7UDRM9jQ5BCxn94ZBmkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T09:40:52Z"
  mac: ENC[AES256_GCM,data:gfa+6np4/iyhlpMg3LCBEMwfXczKsuUxslwDc8v6pIzbMc3OUNkYXNPargenVvh9qzrK4hx5C9BezdHOoOeebvrGMvCueZC3MeROu4Y4T0YiwRPcbCFg5J8iA+f1qZKXkOHkW3+UQhoIlMO55AyNAUloXhdJsz0UElVO476X1+g=,iv:ydE/CFZ3pFaIS5s0vnx2koCcCBLb4Hkr6dMnoz832GM=,tag:8pEy32Jtq1kWkjogX/VNMA==,type:str]
  version: 3.13.1
