apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.github: |
    appID: 4159060
    installationID: 143049164
    privateKey: $github-privateKey
  trigger.on-app-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.spec.source.repoURL contains 'github.com'
      send: [app-deployed]
  template.app-deployed: |
    github:
      checkRun:
        name: "continuous-delivery/{{.app.metadata.name}}"
        details_url: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        status: completed
        conclusion: success
        output:
          title: "Deployment of {{.app.metadata.name}} on ArgoCD"
          summary: "Application {{.app.metadata.name}} is now running new version of deployments manifests."
          text: |
            See more here: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
