apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.github: |
    appID: 4159060
    installationID: 143049164
    privateKey: $github-privateKey
  service.kubernetes.discord: |
    webhook: $webhook-url
  trigger.on-app-deployed: |
    - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.spec.source.repoURL contains 'github.com'
      send: [app-deployed]
  trigger.on-app-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-degraded-discord]
  template.app-deployed: |
    github:
      status:
        state: success
        label: "argocd/{{.app.metadata.name}}"
        targetURL: "https://argocd.tsar-bmb.org/applications/{{.app.metadata.name}}"
  template.app-degraded-discord: |
    discord:
      content: "🚨 **Argo CD Alert: {{.app.metadata.name}} is Degraded!**"
      embeds:
        - title: "Application Status: Degraded"
          description: "The application health check has failed. Please check Argo CD for more details."
          url: "https://argocd.tsar-bmb.org/applications/{{.app.metadata.name}}"
          color: 15158332
