#!/usr/bin/env bash
#MISE description="Decrypt all env files across all packages"
#MISE depends=["env-decrypt:apps:neo-fujimatsu", "env-decrypt:apps:emdash", "env-decrypt:infra:env:prod", "env-decrypt:cmd:discord-gateway-proxy"]
