name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: roppoh-runners
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: oxfmt --check
      - run: lefthook validate
