name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install_args: "bun lefthook"
      - run: bun install --frozen-lockfile --filter "./"
      - parallel:
          - name: Format check (oxfmt)
            run: bun run oxfmt --check
          - name: Validate lefthook
            run: lefthook validate
