name: k8s-ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "k8s/**"
      - ".kube-linter.yaml"
      - ".github/workflows/k8s-ci.yml"
      - "mise.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  k8s:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install_args: "kubeconform kube-linter"
      - parallel:
          - name: kubeconform
            run: kubeconform -summary -ignore-missing-schemas -ignore-filename-pattern 'patches/' -ignore-filename-pattern 'dashboards/' -ignore-filename-pattern 'files/' k8s
          - name: kube-linter
            run: kube-linter lint k8s --config .kube-linter.yaml
