apiVersion: v1
kind: Secret
metadata:
  name: minecraft
  namespace: minecraft
type: Opaque
stringData:
  RCON_PASSWORD: ENC[AES256_GCM,data:9+SBG+sdwW/ivRhUOMCrBh+apKXAAjty8S91dP3MadY=,iv:Sqbi88YRLoDVGPkvRfwtgU1SfrFjLPIde19mKnNCHNw=,tag:4RYle+QYTE0ofpPUzXZXFQ==,type:str]
  #ENC[AES256_GCM,data:NKCphdqXYpqe9q9Mew2u4q8Xh6HTw5qnEVCJ4e5gEfEghfufzj0S4kx4Lt8+/FTrIrIIkikdXQroaO3WJ5Fubic39FgYNy9H6Gov+vWUzhKGdv9T,iv:IWl+yE1xBHq2pGrly5xbV+7tJTZuuZ2jCaz1+SSnOt4=,tag:lWIJhsVZ7KFsXEtsn1PJJQ==,type:comment]
  #ENC[AES256_GCM,data:A9oZIkWkWC3jiYTwz1RRddyUzoN47CPwXJ3IRGUpVAnzbKZsBC45RZbCcYQrZ7RdxMrql2aRgaYiEm5WqWXwhg==,iv:b+XSv4Nj2NSyDJeCOIU+zs33ANbVBSPKGee//tAMxg4=,tag:gnnMGiBRoQdz2zZlnpT7MA==,type:comment]
  #ENC[AES256_GCM,data:FFNQy3otWxJrvYWRUwnvNFo+zxek8TIf91S74h6ocbgxfS8tEtxZZXrF6mfjm1/vYHQ+y0tsJNkIlGqzPMQ=,iv:+JnT/0yLYhgOkt238Cc0jPC87EZgvbB5/UY3en7SNrE=,tag:7ftgmsjHZoOvloAd1fcZqQ==,type:comment]
  R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:OrLarOxL1vb+wczPCZDwewL++yiOV7D3OBl6rUI=,iv:BWshGLwASh2cLFbd5Z3kk7tL6qrol4FDryjVbdwEZDw=,tag:Pc3z+r0EWO6pi2i7d5iTYA==,type:str]
  R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:E55ggHtvCTgBlk/ureUDiKk2wIeGPuUpqyHNaE6656i/,iv:gbyTdSMDosd+qaDpvs7HkqO7xRC62njQniDBsVkKZgU=,tag:9qx06BHjMeCNORyFF5pyNg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVFhwRGhadEJDY0dMWnd6
        Sm4rbVM0cUgwQUZuQ1M4VGFCL3Z3VTRuWGpFCm9ZMWJBTHZ2Y0lGbElJWXZpWXhT
        RGJtL2FEYkdsOGdJdzFwY3VaekJKNVEKLS0tICtNSEU1MUx4TnZEL2ZjNExnRDdi
        bm5SVWdHTGp0bEl1elZtaVBHUzh3bW8KcibAxKDBdLbt2G9JOhm6pwNgTMmP16K3
        VLUd9X7EX8IUJY4D40CSoIaks78mAyES0fwibrteYW216a1sc60nWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNEh4Z0pKNC8ya2txYUcz
        c2UyeExlaDJvamthcHdseG9kc3ZWakVFQVZZCnlmaXEzNFVzWjh6MDBra0c0T1lB
        cDVrSWovbnU3VXZFQS9xU3pIVTBGMjQKLS0tIDUxWVppWER1T2MxZmJYT0dQNmd3
        Rk9zcWFrV09VM2FQbVBXY05oWDc2YjgKkgKITp/RlGRHVb5nGRPcufjiG+EHDMX+
        Kb5Babv+HMLRm9YBWiRmALDnAKzgKDZPRxALCK0MVvq7i5jrtD2J/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T08:45:28Z"
  mac: ENC[AES256_GCM,data:4gBjEsXHQ2bpXd6SGxIxkOx7bjgLTOrYpsOqR860wH3KT0Im7JJ114bsxLVIqo9YiIpqxu5U+RwIxeJazdt+duvDOD2ku9LkPKsVXiYaQ4C4P0LPACxFw38R83KtRInBCh+brOaxDGyXTZm6kuOrGz310yAB2atZdKo/JsIkYW0=,iv:JTcSrUvh6rMbKLdkH6D1ZGnkOqqjUR3AigFrWekUK3M=,tag:yUSvWPmY9IEf7moOT7rnqg==,type:str]
  version: 3.13.1
