apiVersion: v1
kind: Secret
metadata:
  name: minecraft
  namespace: minecraft
type: Opaque
stringData:
  RCON_PASSWORD: ENC[AES256_GCM,data:9+SBG+sdwW/ivRhUOMCrBh+apKXAAjty8S91dP3MadY=,iv:Sqbi88YRLoDVGPkvRfwtgU1SfrFjLPIde19mKnNCHNw=,tag:4RYle+QYTE0ofpPUzXZXFQ==,type:str]
  #ENC[AES256_GCM,data:NKCphdqXYpqe9q9Mew2u4q8Xh6HTw5qnEVCJ4e5gEfEghfufzj0S4kx4Lt8+/FTrIrIIkikdXQroaO3WJ5Fubic39FgYNy9H6Gov+vWUzhKGdv9T,iv:IWl+yE1xBHq2pGrly5xbV+7tJTZuuZ2jCaz1+SSnOt4=,tag:lWIJhsVZ7KFsXEtsn1PJJQ==,type:comment]
  #ENC[AES256_GCM,data:A9oZIkWkWC3jiYTwz1RRddyUzoN47CPwXJ3IRGUpVAnzbKZsBC45RZbCcYQrZ7RdxMrql2aRgaYiEm5WqWXwhg==,iv:b+XSv4Nj2NSyDJeCOIU+zs33ANbVBSPKGee//tAMxg4=,tag:gnnMGiBRoQdz2zZlnpT7MA==,type:comment]
  #ENC[AES256_GCM,data:FFNQy3otWxJrvYWRUwnvNFo+zxek8TIf91S74h6ocbgxfS8tEtxZZXrF6mfjm1/vYHQ+y0tsJNkIlGqzPMQ=,iv:+JnT/0yLYhgOkt238Cc0jPC87EZgvbB5/UY3en7SNrE=,tag:7ftgmsjHZoOvloAd1fcZqQ==,type:comment]
  R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:/ucR17l4Bk1/sJApgRLhuc681Xd3fsYd0v+X4qniOSQ=,iv:QRH52BOK96I5V6TGkqK/pP+z8eKGML/nhgD5+I49FcY=,tag:x4dT2ogI0Ft9zbyKIUIScg==,type:str]
  R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DTAwFWCfXnrt5N5iDyEUUym3R/eR+6+g3k0KfsujgtvtLQonqqHNiGtyJygfzNz80WYobPzFq6+G4p0i9bBHtA==,iv:QCFbumeSNS2Ab17MXV6QKsNWD5283n4Rgd7OlvFWSmU=,tag:WA2mFljqkWzsJ8rpzmOWeA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU243UWJvWlVyZDk1VXBQ
        MHlMTElWRHc5SVAzeUdhbmxIWGV4OGw1TkYwCnZjUGExYzFMZEYyZXAyeUhwMjJW
        SEloN2RlZVZhUlhISEI1TUlZV2dUdjQKLS0tIEZYYnkzUlc0V0lPNWYzeFV6Q1pD
        VDk5WXFrMG1zbTM5NHlxWjJ1d21WUXcKswFNBjsJr4uCucFdJRdqrdh0np6fEap/
        KuHrfJ2/fIHFnB0uke8bUSVPrGclF2PMx8i4oB4az+oyLuHXU0i0Qw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1wref3z28crtwtmd5h570vlrutrrd53r2rdyztaklr5zqwc7kf3msdrjp56
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVzdSWVY0aEV0Mnk4OEt4
        T3BmemRwUXZzN2JEU2tZVmhUWWd1MlVRcUh3CmxxN3hEN2FsNmQyOFJNMWJkL3ho
        b1ZrVzhhdG9ic2diMGVnd2R5TVkyM3cKLS0tIDlONUgvblJlY0M4eGc0d21qbUZZ
        dEF2RVhXUzFpNm54NFdjd3BrbGgzcTAK/V5EB0VqVVFhoQtj+0OewOc7IgClDFXT
        Y5gcOFzOdAEaypSQ5cQ3bdVTRgCO0oDZxLE2X3Tih3Wqn4VJXgY6Tw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age184jtgez9qt5a6d0fq79c9yxuwk2a7d9zkh2ptpld6egawf0xpclqvetfju
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VWJVaTRJd1hhMno5UURF
        QmdOVllrT1hSVVVBdVZCdS9XeWc1YURYWWtnCndwRGxYbk8rcXZXQTlFMDM5VGU2
        cDFFWG5SUXB2QVBZSk5POWxxMUFQMEEKLS0tIHVvcFdpbGoxK1N4K2I2NjlzV1dE
        NmJuZDQ1dk10bGs5L2lDQlZNa0orSHMKGuw6++yXjJyqlimw7pTIWiGtLg110RbL
        nuG3fOAEpCIHj/4RDf8hBI8MACmB21irGuJkQfAPIupNUvtOsFZPqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juv579y80fvm6ewj650l0c75p8wx3daljv5wd7mjdqnjs4zgupzsxal0hc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T09:55:37Z"
  mac: ENC[AES256_GCM,data:5UiuLzcY6gpEW9yWkhj8DwgdewiLn4/yT9n9alngRSCto7deVwn1ZU3IBkRsHq7WKT6dFx9vPUsa7kyFHOI7hCQH8mttwFC7dcYkuPx7tBf3VZe1IcfB2FIARgIbqzAA4a9w4jdF2/oTBSf4twFKmDCK/HffqLql8sqy6jwjS10=,iv:w6ns/jrLZykNln4rDXyPpDLwa3N+riWbmDpanlripb0=,tag:Nv/5cN1rBE0jl8ZLtaaBpQ==,type:str]
  version: 3.13.1
